// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: check_ins.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countCheckInsForPact = `-- name: CountCheckInsForPact :one
select count(*) from check_ins where pact_id = $1
`

func (q *Queries) CountCheckInsForPact(ctx context.Context, pactID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countCheckInsForPact, pactID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countNonFinalCheckIns = `-- name: CountNonFinalCheckIns :one
select count(*) from check_ins where pact_id = $1 and not is_final
`

func (q *Queries) CountNonFinalCheckIns(ctx context.Context, pactID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countNonFinalCheckIns, pactID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getCheckIn = `-- name: GetCheckIn :one
select id, pact_id, member_id, reviewer_id, local_date, status, is_final, cutoff_at, submit_deadline, submitted_at, review_deadline, decided_at, dispute_deadline, disputed_at, resolution_deadline, override_deadline, penalty_applied, created_at, updated_at from check_ins where id = $1
`

func (q *Queries) GetCheckIn(ctx context.Context, id uuid.UUID) (CheckIn, error) {
	row := q.db.QueryRow(ctx, getCheckIn, id)
	var i CheckIn
	err := row.Scan(
		&i.ID,
		&i.PactID,
		&i.MemberID,
		&i.ReviewerID,
		&i.LocalDate,
		&i.Status,
		&i.IsFinal,
		&i.CutoffAt,
		&i.SubmitDeadline,
		&i.SubmittedAt,
		&i.ReviewDeadline,
		&i.DecidedAt,
		&i.DisputeDeadline,
		&i.DisputedAt,
		&i.ResolutionDeadline,
		&i.OverrideDeadline,
		&i.PenaltyApplied,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCheckInForMember = `-- name: GetCheckInForMember :one
select c.id, c.pact_id, c.member_id, c.reviewer_id, c.local_date, c.status, c.is_final, c.cutoff_at, c.submit_deadline, c.submitted_at, c.review_deadline, c.decided_at, c.dispute_deadline, c.disputed_at, c.resolution_deadline, c.override_deadline, c.penalty_applied, c.created_at, c.updated_at from check_ins c
join pact_members m on m.pact_id = c.pact_id and m.user_id = $1
where c.id = $2
`

type GetCheckInForMemberParams struct {
	UserID uuid.UUID
	ID     uuid.UUID
}

func (q *Queries) GetCheckInForMember(ctx context.Context, arg GetCheckInForMemberParams) (CheckIn, error) {
	row := q.db.QueryRow(ctx, getCheckInForMember, arg.UserID, arg.ID)
	var i CheckIn
	err := row.Scan(
		&i.ID,
		&i.PactID,
		&i.MemberID,
		&i.ReviewerID,
		&i.LocalDate,
		&i.Status,
		&i.IsFinal,
		&i.CutoffAt,
		&i.SubmitDeadline,
		&i.SubmittedAt,
		&i.ReviewDeadline,
		&i.DecidedAt,
		&i.DisputeDeadline,
		&i.DisputedAt,
		&i.ResolutionDeadline,
		&i.OverrideDeadline,
		&i.PenaltyApplied,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCheckInForUpdate = `-- name: GetCheckInForUpdate :one
select id, pact_id, member_id, reviewer_id, local_date, status, is_final, cutoff_at, submit_deadline, submitted_at, review_deadline, decided_at, dispute_deadline, disputed_at, resolution_deadline, override_deadline, penalty_applied, created_at, updated_at from check_ins where id = $1 for update
`

func (q *Queries) GetCheckInForUpdate(ctx context.Context, id uuid.UUID) (CheckIn, error) {
	row := q.db.QueryRow(ctx, getCheckInForUpdate, id)
	var i CheckIn
	err := row.Scan(
		&i.ID,
		&i.PactID,
		&i.MemberID,
		&i.ReviewerID,
		&i.LocalDate,
		&i.Status,
		&i.IsFinal,
		&i.CutoffAt,
		&i.SubmitDeadline,
		&i.SubmittedAt,
		&i.ReviewDeadline,
		&i.DecidedAt,
		&i.DisputeDeadline,
		&i.DisputedAt,
		&i.ResolutionDeadline,
		&i.OverrideDeadline,
		&i.PenaltyApplied,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCheckInForUpdateSkipLocked = `-- name: GetCheckInForUpdateSkipLocked :one
select id, pact_id, member_id, reviewer_id, local_date, status, is_final, cutoff_at, submit_deadline, submitted_at, review_deadline, decided_at, dispute_deadline, disputed_at, resolution_deadline, override_deadline, penalty_applied, created_at, updated_at from check_ins where id = $1 for update skip locked
`

// Used by settlement: another worker holding the row means it is being handled.
func (q *Queries) GetCheckInForUpdateSkipLocked(ctx context.Context, id uuid.UUID) (CheckIn, error) {
	row := q.db.QueryRow(ctx, getCheckInForUpdateSkipLocked, id)
	var i CheckIn
	err := row.Scan(
		&i.ID,
		&i.PactID,
		&i.MemberID,
		&i.ReviewerID,
		&i.LocalDate,
		&i.Status,
		&i.IsFinal,
		&i.CutoffAt,
		&i.SubmitDeadline,
		&i.SubmittedAt,
		&i.ReviewDeadline,
		&i.DecidedAt,
		&i.DisputeDeadline,
		&i.DisputedAt,
		&i.ResolutionDeadline,
		&i.OverrideDeadline,
		&i.PenaltyApplied,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

type InsertCheckInsParams struct {
	ID             uuid.UUID
	PactID         uuid.UUID
	MemberID       uuid.UUID
	ReviewerID     uuid.UUID
	LocalDate      time.Time
	CutoffAt       time.Time
	SubmitDeadline time.Time
}

const listCheckInsForPact = `-- name: ListCheckInsForPact :many
select id, pact_id, member_id, reviewer_id, local_date, status, is_final, cutoff_at, submit_deadline, submitted_at, review_deadline, decided_at, dispute_deadline, disputed_at, resolution_deadline, override_deadline, penalty_applied, created_at, updated_at from check_ins
where pact_id = $1 and local_date between $2 and $3
order by local_date, member_id
`

type ListCheckInsForPactParams struct {
	PactID   uuid.UUID
	FromDate time.Time
	ToDate   time.Time
}

func (q *Queries) ListCheckInsForPact(ctx context.Context, arg ListCheckInsForPactParams) ([]CheckIn, error) {
	rows, err := q.db.Query(ctx, listCheckInsForPact, arg.PactID, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CheckIn{}
	for rows.Next() {
		var i CheckIn
		if err := rows.Scan(
			&i.ID,
			&i.PactID,
			&i.MemberID,
			&i.ReviewerID,
			&i.LocalDate,
			&i.Status,
			&i.IsFinal,
			&i.CutoffAt,
			&i.SubmitDeadline,
			&i.SubmittedAt,
			&i.ReviewDeadline,
			&i.DecidedAt,
			&i.DisputeDeadline,
			&i.DisputedAt,
			&i.ResolutionDeadline,
			&i.OverrideDeadline,
			&i.PenaltyApplied,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDueCheckInIDs = `-- name: ListDueCheckInIDs :many
select id from check_ins
where not is_final and (
     (status = 'open'          and submit_deadline     < $1::timestamptz)
  or (status = 'submitted'     and review_deadline     < $1::timestamptz)
  or (status = 'auto_approved' and override_deadline   < $1::timestamptz)
  or (status = 'rejected'      and dispute_deadline    < $1::timestamptz)
  or (status = 'disputed'      and resolution_deadline < $1::timestamptz)
)
order by case status
  when 'open' then submit_deadline
  when 'submitted' then review_deadline
  when 'auto_approved' then override_deadline
  when 'rejected' then dispute_deadline
  else resolution_deadline
end
limit $2
`

type ListDueCheckInIDsParams struct {
	Now     time.Time
	MaxRows int32
}

// Every check-in with a passed deadline, oldest deadline first (SPEC §7 steps 1-5).
func (q *Queries) ListDueCheckInIDs(ctx context.Context, arg ListDueCheckInIDsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listDueCheckInIDs, arg.Now, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenCheckInsForMember = `-- name: ListOpenCheckInsForMember :many
select c.id, c.pact_id, c.member_id, c.reviewer_id, c.local_date, c.status, c.is_final, c.cutoff_at, c.submit_deadline, c.submitted_at, c.review_deadline, c.decided_at, c.dispute_deadline, c.disputed_at, c.resolution_deadline, c.override_deadline, c.penalty_applied, c.created_at, c.updated_at, p.title as pact_title from check_ins c
join pacts p on p.id = c.pact_id
where c.member_id = $1 and p.status = 'active' and not c.is_final
  and c.cutoff_at between $2 and $3
order by c.cutoff_at
`

type ListOpenCheckInsForMemberParams struct {
	MemberID uuid.UUID
	FromTime time.Time
	ToTime   time.Time
}

type ListOpenCheckInsForMemberRow struct {
	ID                 uuid.UUID
	PactID             uuid.UUID
	MemberID           uuid.UUID
	ReviewerID         uuid.UUID
	LocalDate          time.Time
	Status             string
	IsFinal            bool
	CutoffAt           time.Time
	SubmitDeadline     time.Time
	SubmittedAt        *time.Time
	ReviewDeadline     *time.Time
	DecidedAt          *time.Time
	DisputeDeadline    *time.Time
	DisputedAt         *time.Time
	ResolutionDeadline *time.Time
	OverrideDeadline   *time.Time
	PenaltyApplied     bool
	CreatedAt          time.Time
	UpdatedAt          time.Time
	PactTitle          string
}

func (q *Queries) ListOpenCheckInsForMember(ctx context.Context, arg ListOpenCheckInsForMemberParams) ([]ListOpenCheckInsForMemberRow, error) {
	rows, err := q.db.Query(ctx, listOpenCheckInsForMember, arg.MemberID, arg.FromTime, arg.ToTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOpenCheckInsForMemberRow{}
	for rows.Next() {
		var i ListOpenCheckInsForMemberRow
		if err := rows.Scan(
			&i.ID,
			&i.PactID,
			&i.MemberID,
			&i.ReviewerID,
			&i.LocalDate,
			&i.Status,
			&i.IsFinal,
			&i.CutoffAt,
			&i.SubmitDeadline,
			&i.SubmittedAt,
			&i.ReviewDeadline,
			&i.DecidedAt,
			&i.DisputeDeadline,
			&i.DisputedAt,
			&i.ResolutionDeadline,
			&i.OverrideDeadline,
			&i.PenaltyApplied,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PactTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviewQueue = `-- name: ListReviewQueue :many
select c.id, c.pact_id, c.member_id, c.reviewer_id, c.local_date, c.status, c.is_final, c.cutoff_at, c.submit_deadline, c.submitted_at, c.review_deadline, c.decided_at, c.dispute_deadline, c.disputed_at, c.resolution_deadline, c.override_deadline, c.penalty_applied, c.created_at, c.updated_at, p.title as pact_title from check_ins c
join pacts p on p.id = c.pact_id
where c.reviewer_id = $1 and c.status = 'submitted'
order by c.review_deadline
`

type ListReviewQueueRow struct {
	ID                 uuid.UUID
	PactID             uuid.UUID
	MemberID           uuid.UUID
	ReviewerID         uuid.UUID
	LocalDate          time.Time
	Status             string
	IsFinal            bool
	CutoffAt           time.Time
	SubmitDeadline     time.Time
	SubmittedAt        *time.Time
	ReviewDeadline     *time.Time
	DecidedAt          *time.Time
	DisputeDeadline    *time.Time
	DisputedAt         *time.Time
	ResolutionDeadline *time.Time
	OverrideDeadline   *time.Time
	PenaltyApplied     bool
	CreatedAt          time.Time
	UpdatedAt          time.Time
	PactTitle          string
}

func (q *Queries) ListReviewQueue(ctx context.Context, reviewerID uuid.UUID) ([]ListReviewQueueRow, error) {
	rows, err := q.db.Query(ctx, listReviewQueue, reviewerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReviewQueueRow{}
	for rows.Next() {
		var i ListReviewQueueRow
		if err := rows.Scan(
			&i.ID,
			&i.PactID,
			&i.MemberID,
			&i.ReviewerID,
			&i.LocalDate,
			&i.Status,
			&i.IsFinal,
			&i.CutoffAt,
			&i.SubmitDeadline,
			&i.SubmittedAt,
			&i.ReviewDeadline,
			&i.DecidedAt,
			&i.DisputeDeadline,
			&i.DisputedAt,
			&i.ResolutionDeadline,
			&i.OverrideDeadline,
			&i.PenaltyApplied,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PactTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCheckInState = `-- name: UpdateCheckInState :execrows
update check_ins
set status = $1, is_final = $2,
    submitted_at = $3, review_deadline = $4,
    decided_at = $5, dispute_deadline = $6,
    disputed_at = $7, resolution_deadline = $8,
    override_deadline = $9, penalty_applied = $10,
    updated_at = now()
where id = $11 and status = $12 and is_final = $13
`

type UpdateCheckInStateParams struct {
	Status             string
	IsFinal            bool
	SubmittedAt        *time.Time
	ReviewDeadline     *time.Time
	DecidedAt          *time.Time
	DisputeDeadline    *time.Time
	DisputedAt         *time.Time
	ResolutionDeadline *time.Time
	OverrideDeadline   *time.Time
	PenaltyApplied     bool
	ID                 uuid.UUID
	ExpectedStatus     string
	ExpectedFinal      bool
}

// Writes every mutable field, guarded by the status the transition started from
// (optimistic check, SPEC §7). 0 rows = someone else moved it first.
func (q *Queries) UpdateCheckInState(ctx context.Context, arg UpdateCheckInStateParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateCheckInState,
		arg.Status,
		arg.IsFinal,
		arg.SubmittedAt,
		arg.ReviewDeadline,
		arg.DecidedAt,
		arg.DisputeDeadline,
		arg.DisputedAt,
		arg.ResolutionDeadline,
		arg.OverrideDeadline,
		arg.PenaltyApplied,
		arg.ID,
		arg.ExpectedStatus,
		arg.ExpectedFinal,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
