// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copyfrom.go

package store

import (
	"context"
)

// iteratorForInsertCheckIns implements pgx.CopyFromSource.
type iteratorForInsertCheckIns struct {
	rows                 []InsertCheckInsParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertCheckIns) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertCheckIns) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].PactID,
		r.rows[0].MemberID,
		r.rows[0].ReviewerID,
		r.rows[0].LocalDate,
		r.rows[0].CutoffAt,
		r.rows[0].SubmitDeadline,
	}, nil
}

func (r iteratorForInsertCheckIns) Err() error {
	return nil
}

func (q *Queries) InsertCheckIns(ctx context.Context, arg []InsertCheckInsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"check_ins"}, []string{"id", "pact_id", "member_id", "reviewer_id", "local_date", "cutoff_at", "submit_deadline"}, &iteratorForInsertCheckIns{rows: arg})
}
