// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ledger.sql

package store

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimDigestNotifications = `-- name: ClaimDigestNotifications :many
update notifications set emailed_at = now()
where user_id = $1 and kind = $2 and emailed_at is null and payload->>'pact_id' = $3::text
returning id
`

type ClaimDigestNotificationsParams struct {
	UserID uuid.UUID
	Kind   string
	PactID string
}

// Claims every not-yet-emailed notification of one kind for a user and pact.
func (q *Queries) ClaimDigestNotifications(ctx context.Context, arg ClaimDigestNotificationsParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, claimDigestNotifications, arg.UserID, arg.Kind, arg.PactID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const claimNotificationEmail = `-- name: ClaimNotificationEmail :one
with c as (
  update notifications set emailed_at = now()
  where notifications.id = $1 and notifications.emailed_at is null
  returning notifications.id, notifications.user_id, notifications.kind, notifications.payload
)
select c.id, c.kind, c.payload, u.email, u.display_name, u.locale
from c join users u on u.id = c.user_id
`

type ClaimNotificationEmailRow struct {
	ID          int64
	Kind        string
	Payload     json.RawMessage
	Email       string
	DisplayName string
	Locale      string
}

// Claims one notification for emailing and returns what the mail needs. No row: already
// claimed or sent, or the notification is gone.
func (q *Queries) ClaimNotificationEmail(ctx context.Context, id int64) (ClaimNotificationEmailRow, error) {
	row := q.db.QueryRow(ctx, claimNotificationEmail, id)
	var i ClaimNotificationEmailRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Payload,
		&i.Email,
		&i.DisplayName,
		&i.Locale,
	)
	return i, err
}

const confirmPayout = `-- name: ConfirmPayout :execrows
update payouts set confirmed_at = now() where pact_id = $1 and confirmed_at is null
`

func (q *Queries) ConfirmPayout(ctx context.Context, pactID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, confirmPayout, pactID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countUnreadNotifications = `-- name: CountUnreadNotifications :one
select count(*) from notifications where user_id = $1 and read_at is null
`

func (q *Queries) CountUnreadNotifications(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreadNotifications, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPayout = `-- name: CreatePayout :exec
insert into payouts (pact_id, amount) values ($1, $2) on conflict (pact_id) do nothing
`

type CreatePayoutParams struct {
	PactID uuid.UUID
	Amount int64
}

func (q *Queries) CreatePayout(ctx context.Context, arg CreatePayoutParams) error {
	_, err := q.db.Exec(ctx, createPayout, arg.PactID, arg.Amount)
	return err
}

const fetchPendingOutbox = `-- name: FetchPendingOutbox :many
select id, topic, payload, created_at, dispatched_at from outbox where dispatched_at is null order by id limit $1 for update skip locked
`

func (q *Queries) FetchPendingOutbox(ctx context.Context, limit int32) ([]Outbox, error) {
	rows, err := q.db.Query(ctx, fetchPendingOutbox, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Outbox{}
	for rows.Next() {
		var i Outbox
		if err := rows.Scan(
			&i.ID,
			&i.Topic,
			&i.Payload,
			&i.CreatedAt,
			&i.DispatchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLedgerEntryByKey = `-- name: GetLedgerEntryByKey :one
select id, pact_id, kind, amount, check_in_id, reverses_entry_id, idempotency_key, note, created_at from ledger_entries where idempotency_key = $1
`

func (q *Queries) GetLedgerEntryByKey(ctx context.Context, idempotencyKey string) (LedgerEntry, error) {
	row := q.db.QueryRow(ctx, getLedgerEntryByKey, idempotencyKey)
	var i LedgerEntry
	err := row.Scan(
		&i.ID,
		&i.PactID,
		&i.Kind,
		&i.Amount,
		&i.CheckInID,
		&i.ReversesEntryID,
		&i.IdempotencyKey,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const getPayout = `-- name: GetPayout :one
select pact_id, amount, marked_paid_at, marked_paid_note, confirmed_at, created_at from payouts where pact_id = $1
`

func (q *Queries) GetPayout(ctx context.Context, pactID uuid.UUID) (Payout, error) {
	row := q.db.QueryRow(ctx, getPayout, pactID)
	var i Payout
	err := row.Scan(
		&i.PactID,
		&i.Amount,
		&i.MarkedPaidAt,
		&i.MarkedPaidNote,
		&i.ConfirmedAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertLedgerEntry = `-- name: InsertLedgerEntry :one
insert into ledger_entries (pact_id, kind, amount, check_in_id, reverses_entry_id, idempotency_key, note)
values ($1, $2, $3, $4, $5, $6, $7)
on conflict (idempotency_key) do nothing
returning id, pact_id, kind, amount, check_in_id, reverses_entry_id, idempotency_key, note, created_at
`

type InsertLedgerEntryParams struct {
	PactID          uuid.UUID
	Kind            string
	Amount          int64
	CheckInID       *uuid.UUID
	ReversesEntryID *int64
	IdempotencyKey  string
	Note            *string
}

// Idempotent insert: returns no row (pgx.ErrNoRows) when the key already exists (SPEC §6 L3).
func (q *Queries) InsertLedgerEntry(ctx context.Context, arg InsertLedgerEntryParams) (LedgerEntry, error) {
	row := q.db.QueryRow(ctx, insertLedgerEntry,
		arg.PactID,
		arg.Kind,
		arg.Amount,
		arg.CheckInID,
		arg.ReversesEntryID,
		arg.IdempotencyKey,
		arg.Note,
	)
	var i LedgerEntry
	err := row.Scan(
		&i.ID,
		&i.PactID,
		&i.Kind,
		&i.Amount,
		&i.CheckInID,
		&i.ReversesEntryID,
		&i.IdempotencyKey,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const insertNotification = `-- name: InsertNotification :one
insert into notifications (user_id, kind, payload) values ($1, $2, $3) returning id
`

type InsertNotificationParams struct {
	UserID  uuid.UUID
	Kind    string
	Payload json.RawMessage
}

func (q *Queries) InsertNotification(ctx context.Context, arg InsertNotificationParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertNotification, arg.UserID, arg.Kind, arg.Payload)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertOutbox = `-- name: InsertOutbox :exec
insert into outbox (topic, payload) values ($1, $2)
`

type InsertOutboxParams struct {
	Topic   string
	Payload json.RawMessage
}

func (q *Queries) InsertOutbox(ctx context.Context, arg InsertOutboxParams) error {
	_, err := q.db.Exec(ctx, insertOutbox, arg.Topic, arg.Payload)
	return err
}

const listLedgerPage = `-- name: ListLedgerPage :many
select id, pact_id, kind, amount, check_in_id, reverses_entry_id, idempotency_key, note, created_at, balance_after, check_in_local_date, check_in_member_id from (
  select l.id, l.pact_id, l.kind, l.amount, l.check_in_id, l.reverses_entry_id, l.idempotency_key, l.note, l.created_at,
         (sum(l.amount) over (order by l.id))::bigint as balance_after,
         c.local_date as check_in_local_date, c.member_id as check_in_member_id
  from ledger_entries l
  left join check_ins c on c.id = l.check_in_id
  where l.pact_id = $1
) page
where $2::bigint is null or page.id < $2::bigint
order by page.id desc
limit $3
`

type ListLedgerPageParams struct {
	PactID   uuid.UUID
	BeforeID *int64
	MaxRows  int32
}

type ListLedgerPageRow struct {
	ID               int64
	PactID           uuid.UUID
	Kind             string
	Amount           int64
	CheckInID        *uuid.UUID
	ReversesEntryID  *int64
	IdempotencyKey   string
	Note             *string
	CreatedAt        time.Time
	BalanceAfter     int64
	CheckInLocalDate pgtype.Date
	CheckInMemberID  *uuid.UUID
}

// Passbook page, newest first, with the running balance after each line. The window
// runs over the whole pact ledger before the cursor filter, so every page agrees.
// The check-in join only adds the day and member a line is about.
func (q *Queries) ListLedgerPage(ctx context.Context, arg ListLedgerPageParams) ([]ListLedgerPageRow, error) {
	rows, err := q.db.Query(ctx, listLedgerPage, arg.PactID, arg.BeforeID, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLedgerPageRow{}
	for rows.Next() {
		var i ListLedgerPageRow
		if err := rows.Scan(
			&i.ID,
			&i.PactID,
			&i.Kind,
			&i.Amount,
			&i.CheckInID,
			&i.ReversesEntryID,
			&i.IdempotencyKey,
			&i.Note,
			&i.CreatedAt,
			&i.BalanceAfter,
			&i.CheckInLocalDate,
			&i.CheckInMemberID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotifications = `-- name: ListNotifications :many
select id, user_id, kind, payload, read_at, created_at, emailed_at from notifications
where user_id = $1
  and ($2::bigint is null or id < $2::bigint)
  and (not $3::boolean or read_at is null)
order by id desc
limit $4
`

type ListNotificationsParams struct {
	UserID     uuid.UUID
	BeforeID   *int64
	UnreadOnly bool
	MaxRows    int32
}

func (q *Queries) ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNotifications,
		arg.UserID,
		arg.BeforeID,
		arg.UnreadOnly,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Kind,
			&i.Payload,
			&i.ReadAt,
			&i.CreatedAt,
			&i.EmailedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPayoutsForPacts = `-- name: ListPayoutsForPacts :many
select pact_id, amount, marked_paid_at, marked_paid_note, confirmed_at, created_at from payouts where pact_id = any($1::uuid[])
`

func (q *Queries) ListPayoutsForPacts(ctx context.Context, pactIds []uuid.UUID) ([]Payout, error) {
	rows, err := q.db.Query(ctx, listPayoutsForPacts, pactIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Payout{}
	for rows.Next() {
		var i Payout
		if err := rows.Scan(
			&i.PactID,
			&i.Amount,
			&i.MarkedPaidAt,
			&i.MarkedPaidNote,
			&i.ConfirmedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNotificationsRead = `-- name: MarkNotificationsRead :exec
update notifications set read_at = now() where user_id = $1 and id = any($2::bigint[]) and read_at is null
`

type MarkNotificationsReadParams struct {
	UserID uuid.UUID
	Ids    []int64
}

func (q *Queries) MarkNotificationsRead(ctx context.Context, arg MarkNotificationsReadParams) error {
	_, err := q.db.Exec(ctx, markNotificationsRead, arg.UserID, arg.Ids)
	return err
}

const markOutboxDispatched = `-- name: MarkOutboxDispatched :exec
update outbox set dispatched_at = now(), payload = payload - 'token' where id = any($1::bigint[])
`

// An invite mail row carries the plaintext invite token until it is relayed; drop it here so
// only the hash stays in the database.
func (q *Queries) MarkOutboxDispatched(ctx context.Context, ids []int64) error {
	_, err := q.db.Exec(ctx, markOutboxDispatched, ids)
	return err
}

const markPayoutPaid = `-- name: MarkPayoutPaid :execrows
update payouts set marked_paid_at = now(), marked_paid_note = $2 where pact_id = $1 and marked_paid_at is null
`

type MarkPayoutPaidParams struct {
	PactID         uuid.UUID
	MarkedPaidNote *string
}

func (q *Queries) MarkPayoutPaid(ctx context.Context, arg MarkPayoutPaidParams) (int64, error) {
	result, err := q.db.Exec(ctx, markPayoutPaid, arg.PactID, arg.MarkedPaidNote)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const potBalance = `-- name: PotBalance :one
select coalesce(sum(amount), 0)::bigint as balance from ledger_entries where pact_id = $1
`

// Pot balance is always the sum of the ledger (SPEC §6 L1).
func (q *Queries) PotBalance(ctx context.Context, pactID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, potBalance, pactID)
	var balance int64
	err := row.Scan(&balance)
	return balance, err
}

const potBalances = `-- name: PotBalances :many
select pact_id, coalesce(sum(amount), 0)::bigint as balance from ledger_entries
where pact_id = any($1::uuid[])
group by pact_id
`

type PotBalancesRow struct {
	PactID  uuid.UUID
	Balance int64
}

// Balances for several pacts at once (list and Today screens).
func (q *Queries) PotBalances(ctx context.Context, pactIds []uuid.UUID) ([]PotBalancesRow, error) {
	rows, err := q.db.Query(ctx, potBalances, pactIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PotBalancesRow{}
	for rows.Next() {
		var i PotBalancesRow
		if err := rows.Scan(&i.PactID, &i.Balance); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseNotificationEmail = `-- name: ReleaseNotificationEmail :exec
update notifications set emailed_at = null where id = any($1::bigint[])
`

func (q *Queries) ReleaseNotificationEmail(ctx context.Context, ids []int64) error {
	_, err := q.db.Exec(ctx, releaseNotificationEmail, ids)
	return err
}
