// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type Attachment struct {
	ID            uuid.UUID
	OwnerID       uuid.UUID
	PactID        uuid.UUID
	ProofID       *uuid.UUID
	Kind          string
	Status        string
	StagingKey    *string
	MediaKey      *string
	ThumbKey      *string
	DeclaredMime  *string
	SniffedMime   *string
	DeclaredBytes *int64
	StoredBytes   *int64
	Width         *int32
	Height        *int32
	DurationMs    *int32
	RejectReason  *string
	CreatedAt     time.Time
	ReadyAt       *time.Time
}

type CheckIn struct {
	ID                 uuid.UUID
	PactID             uuid.UUID
	MemberID           uuid.UUID
	ReviewerID         uuid.UUID
	LocalDate          time.Time
	Status             string
	IsFinal            bool
	CutoffAt           time.Time
	SubmitDeadline     time.Time
	SubmittedAt        *time.Time
	ReviewDeadline     *time.Time
	DecidedAt          *time.Time
	DisputeDeadline    *time.Time
	DisputedAt         *time.Time
	ResolutionDeadline *time.Time
	OverrideDeadline   *time.Time
	PenaltyApplied     bool
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

type Decision struct {
	ID        int64
	CheckInID uuid.UUID
	ActorID   *uuid.UUID
	Action    string
	Reason    *string
	CreatedAt time.Time
}

type LedgerEntry struct {
	ID              int64
	PactID          uuid.UUID
	Kind            string
	Amount          int64
	CheckInID       *uuid.UUID
	ReversesEntryID *int64
	IdempotencyKey  string
	Note            *string
	CreatedAt       time.Time
}

type Notification struct {
	ID        int64
	UserID    uuid.UUID
	Kind      string
	Payload   json.RawMessage
	ReadAt    *time.Time
	CreatedAt time.Time
	EmailedAt *time.Time
}

type Outbox struct {
	ID           int64
	Topic        string
	Payload      json.RawMessage
	CreatedAt    time.Time
	DispatchedAt *time.Time
}

type Pact struct {
	ID            uuid.UUID
	Title         string
	Description   *string
	Status        string
	CreatedBy     uuid.UUID
	BackerID      uuid.UUID
	Terms         json.RawMessage
	TermsVersion  int32
	TermsHash     string
	Timezone      string
	StartsOn      time.Time
	EndsOn        time.Time
	OverridesUsed int32
	ScheduledAt   *time.Time
	SettledAt     *time.Time
	CompletedAt   *time.Time
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type PactInvite struct {
	TokenHash string
	PactID    uuid.UUID
	Email     *string
	ExpiresAt time.Time
	UsedAt    *time.Time
	CreatedAt time.Time
	EmailedAt *time.Time
}

type PactMember struct {
	PactID            uuid.UUID
	UserID            uuid.UUID
	Role              string
	LineColor         string
	AcceptedTermsHash *string
	AcceptedAt        *time.Time
	SignatureName     *string
	RestDaysUsed      int32
}

type Payout struct {
	PactID         uuid.UUID
	Amount         int64
	MarkedPaidAt   *time.Time
	MarkedPaidNote *string
	ConfirmedAt    *time.Time
	CreatedAt      time.Time
}

type Proof struct {
	ID        uuid.UUID
	CheckInID uuid.UUID
	Version   int32
	BodyDoc   json.RawMessage
	BodyText  string
	WordCount int32
	Links     json.RawMessage
	CreatedAt time.Time
}

type RemindersSent struct {
	CheckInID uuid.UUID
	Kind      string
	SentAt    time.Time
}

type User struct {
	ID              uuid.UUID
	Email           string
	PasswordHash    string
	DisplayName     string
	Locale          string
	Timezone        string
	AvatarKey       *string
	EmailVerifiedAt *time.Time
	CreatedAt       time.Time
	EmailOff        []string
}
