// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pacts.sql

package store

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const acceptTerms = `-- name: AcceptTerms :execrows
update pact_members
set accepted_terms_hash = $1, accepted_at = now(), signature_name = $2
where pact_id = $3 and user_id = $4
`

type AcceptTermsParams struct {
	TermsHash     *string
	SignatureName *string
	PactID        uuid.UUID
	UserID        uuid.UUID
}

func (q *Queries) AcceptTerms(ctx context.Context, arg AcceptTermsParams) (int64, error) {
	result, err := q.db.Exec(ctx, acceptTerms,
		arg.TermsHash,
		arg.SignatureName,
		arg.PactID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const activateDuePacts = `-- name: ActivateDuePacts :many
update pacts
set status = 'active', updated_at = now()
where status = 'scheduled'
  and ($1::timestamptz at time zone timezone)::date >= starts_on
returning id
`

func (q *Queries) ActivateDuePacts(ctx context.Context, now time.Time) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, activateDuePacts, now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const addPactMember = `-- name: AddPactMember :exec
insert into pact_members (pact_id, user_id, role, line_color)
values ($1, $2, $3, $4)
`

type AddPactMemberParams struct {
	PactID    uuid.UUID
	UserID    uuid.UUID
	Role      string
	LineColor string
}

func (q *Queries) AddPactMember(ctx context.Context, arg AddPactMemberParams) error {
	_, err := q.db.Exec(ctx, addPactMember,
		arg.PactID,
		arg.UserID,
		arg.Role,
		arg.LineColor,
	)
	return err
}

const countAcceptances = `-- name: CountAcceptances :one
select count(*) from pact_members where pact_id = $1 and accepted_terms_hash = $2
`

type CountAcceptancesParams struct {
	PactID    uuid.UUID
	TermsHash *string
}

func (q *Queries) CountAcceptances(ctx context.Context, arg CountAcceptancesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAcceptances, arg.PactID, arg.TermsHash)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOpenPactsForUser = `-- name: CountOpenPactsForUser :one
select count(*) from pacts p
join pact_members m on m.pact_id = p.id
where m.user_id = $1 and p.status not in ('completed', 'cancelled')
`

func (q *Queries) CountOpenPactsForUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countOpenPactsForUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createInvite = `-- name: CreateInvite :exec
insert into pact_invites (token_hash, pact_id, email, expires_at) values ($1, $2, $3, $4)
`

type CreateInviteParams struct {
	TokenHash string
	PactID    uuid.UUID
	Email     *string
	ExpiresAt time.Time
}

func (q *Queries) CreateInvite(ctx context.Context, arg CreateInviteParams) error {
	_, err := q.db.Exec(ctx, createInvite,
		arg.TokenHash,
		arg.PactID,
		arg.Email,
		arg.ExpiresAt,
	)
	return err
}

const createPact = `-- name: CreatePact :one
insert into pacts (id, title, description, created_by, backer_id, terms, terms_hash, timezone, starts_on, ends_on)
values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
returning id, title, description, status, created_by, backer_id, terms, terms_version, terms_hash, timezone, starts_on, ends_on, overrides_used, scheduled_at, settled_at, completed_at, created_at, updated_at
`

type CreatePactParams struct {
	ID          uuid.UUID
	Title       string
	Description *string
	CreatedBy   uuid.UUID
	BackerID    uuid.UUID
	Terms       json.RawMessage
	TermsHash   string
	Timezone    string
	StartsOn    time.Time
	EndsOn      time.Time
}

func (q *Queries) CreatePact(ctx context.Context, arg CreatePactParams) (Pact, error) {
	row := q.db.QueryRow(ctx, createPact,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.CreatedBy,
		arg.BackerID,
		arg.Terms,
		arg.TermsHash,
		arg.Timezone,
		arg.StartsOn,
		arg.EndsOn,
	)
	var i Pact
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.CreatedBy,
		&i.BackerID,
		&i.Terms,
		&i.TermsVersion,
		&i.TermsHash,
		&i.Timezone,
		&i.StartsOn,
		&i.EndsOn,
		&i.OverridesUsed,
		&i.ScheduledAt,
		&i.SettledAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInvite = `-- name: GetInvite :one
select token_hash, pact_id, email, expires_at, used_at, created_at from pact_invites where token_hash = $1
`

func (q *Queries) GetInvite(ctx context.Context, tokenHash string) (PactInvite, error) {
	row := q.db.QueryRow(ctx, getInvite, tokenHash)
	var i PactInvite
	err := row.Scan(
		&i.TokenHash,
		&i.PactID,
		&i.Email,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPact = `-- name: GetPact :one
select id, title, description, status, created_by, backer_id, terms, terms_version, terms_hash, timezone, starts_on, ends_on, overrides_used, scheduled_at, settled_at, completed_at, created_at, updated_at from pacts where id = $1
`

func (q *Queries) GetPact(ctx context.Context, id uuid.UUID) (Pact, error) {
	row := q.db.QueryRow(ctx, getPact, id)
	var i Pact
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.CreatedBy,
		&i.BackerID,
		&i.Terms,
		&i.TermsVersion,
		&i.TermsHash,
		&i.Timezone,
		&i.StartsOn,
		&i.EndsOn,
		&i.OverridesUsed,
		&i.ScheduledAt,
		&i.SettledAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPactForMember = `-- name: GetPactForMember :one
select p.id, p.title, p.description, p.status, p.created_by, p.backer_id, p.terms, p.terms_version, p.terms_hash, p.timezone, p.starts_on, p.ends_on, p.overrides_used, p.scheduled_at, p.settled_at, p.completed_at, p.created_at, p.updated_at from pacts p
join pact_members m on m.pact_id = p.id and m.user_id = $1
where p.id = $2
`

type GetPactForMemberParams struct {
	UserID uuid.UUID
	PactID uuid.UUID
}

// Membership-filtered read (AGENTS.md invariant 8): no row for non-members.
func (q *Queries) GetPactForMember(ctx context.Context, arg GetPactForMemberParams) (Pact, error) {
	row := q.db.QueryRow(ctx, getPactForMember, arg.UserID, arg.PactID)
	var i Pact
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.CreatedBy,
		&i.BackerID,
		&i.Terms,
		&i.TermsVersion,
		&i.TermsHash,
		&i.Timezone,
		&i.StartsOn,
		&i.EndsOn,
		&i.OverridesUsed,
		&i.ScheduledAt,
		&i.SettledAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPactForUpdate = `-- name: GetPactForUpdate :one
select id, title, description, status, created_by, backer_id, terms, terms_version, terms_hash, timezone, starts_on, ends_on, overrides_used, scheduled_at, settled_at, completed_at, created_at, updated_at from pacts where id = $1 for update
`

// Locks the pact row: serialises ledger clamps and counters for one pact (ADR-0002).
func (q *Queries) GetPactForUpdate(ctx context.Context, id uuid.UUID) (Pact, error) {
	row := q.db.QueryRow(ctx, getPactForUpdate, id)
	var i Pact
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.CreatedBy,
		&i.BackerID,
		&i.Terms,
		&i.TermsVersion,
		&i.TermsHash,
		&i.Timezone,
		&i.StartsOn,
		&i.EndsOn,
		&i.OverridesUsed,
		&i.ScheduledAt,
		&i.SettledAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPactMember = `-- name: GetPactMember :one
select pact_id, user_id, role, line_color, accepted_terms_hash, accepted_at, signature_name, rest_days_used from pact_members where pact_id = $1 and user_id = $2
`

type GetPactMemberParams struct {
	PactID uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetPactMember(ctx context.Context, arg GetPactMemberParams) (PactMember, error) {
	row := q.db.QueryRow(ctx, getPactMember, arg.PactID, arg.UserID)
	var i PactMember
	err := row.Scan(
		&i.PactID,
		&i.UserID,
		&i.Role,
		&i.LineColor,
		&i.AcceptedTermsHash,
		&i.AcceptedAt,
		&i.SignatureName,
		&i.RestDaysUsed,
	)
	return i, err
}

const incrementOverridesUsed = `-- name: IncrementOverridesUsed :exec
update pacts set overrides_used = overrides_used + 1, updated_at = now() where id = $1
`

func (q *Queries) IncrementOverridesUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, incrementOverridesUsed, id)
	return err
}

const incrementRestDaysUsed = `-- name: IncrementRestDaysUsed :exec
update pact_members set rest_days_used = rest_days_used + 1 where pact_id = $1 and user_id = $2
`

type IncrementRestDaysUsedParams struct {
	PactID uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) IncrementRestDaysUsed(ctx context.Context, arg IncrementRestDaysUsedParams) error {
	_, err := q.db.Exec(ctx, incrementRestDaysUsed, arg.PactID, arg.UserID)
	return err
}

const listMembersForPacts = `-- name: ListMembersForPacts :many
select m.pact_id, m.user_id, m.role, m.line_color, m.accepted_terms_hash, m.accepted_at, m.signature_name, m.rest_days_used, u.display_name, u.email from pact_members m
join users u on u.id = m.user_id
where m.pact_id = any($1::uuid[])
order by m.pact_id, m.role
`

type ListMembersForPactsRow struct {
	PactID            uuid.UUID
	UserID            uuid.UUID
	Role              string
	LineColor         string
	AcceptedTermsHash *string
	AcceptedAt        *time.Time
	SignatureName     *string
	RestDaysUsed      int32
	DisplayName       string
	Email             string
}

func (q *Queries) ListMembersForPacts(ctx context.Context, pactIds []uuid.UUID) ([]ListMembersForPactsRow, error) {
	rows, err := q.db.Query(ctx, listMembersForPacts, pactIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMembersForPactsRow{}
	for rows.Next() {
		var i ListMembersForPactsRow
		if err := rows.Scan(
			&i.PactID,
			&i.UserID,
			&i.Role,
			&i.LineColor,
			&i.AcceptedTermsHash,
			&i.AcceptedAt,
			&i.SignatureName,
			&i.RestDaysUsed,
			&i.DisplayName,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPactMembers = `-- name: ListPactMembers :many
select m.pact_id, m.user_id, m.role, m.line_color, m.accepted_terms_hash, m.accepted_at, m.signature_name, m.rest_days_used, u.display_name, u.email from pact_members m
join users u on u.id = m.user_id
where m.pact_id = $1
order by m.role
`

type ListPactMembersRow struct {
	PactID            uuid.UUID
	UserID            uuid.UUID
	Role              string
	LineColor         string
	AcceptedTermsHash *string
	AcceptedAt        *time.Time
	SignatureName     *string
	RestDaysUsed      int32
	DisplayName       string
	Email             string
}

func (q *Queries) ListPactMembers(ctx context.Context, pactID uuid.UUID) ([]ListPactMembersRow, error) {
	rows, err := q.db.Query(ctx, listPactMembers, pactID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPactMembersRow{}
	for rows.Next() {
		var i ListPactMembersRow
		if err := rows.Scan(
			&i.PactID,
			&i.UserID,
			&i.Role,
			&i.LineColor,
			&i.AcceptedTermsHash,
			&i.AcceptedAt,
			&i.SignatureName,
			&i.RestDaysUsed,
			&i.DisplayName,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPactsForUser = `-- name: ListPactsForUser :many
select p.id, p.title, p.description, p.status, p.created_by, p.backer_id, p.terms, p.terms_version, p.terms_hash, p.timezone, p.starts_on, p.ends_on, p.overrides_used, p.scheduled_at, p.settled_at, p.completed_at, p.created_at, p.updated_at from pacts p
join pact_members m on m.pact_id = p.id
where m.user_id = $1
order by p.created_at desc
`

func (q *Queries) ListPactsForUser(ctx context.Context, userID uuid.UUID) ([]Pact, error) {
	rows, err := q.db.Query(ctx, listPactsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Pact{}
	for rows.Next() {
		var i Pact
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.CreatedBy,
			&i.BackerID,
			&i.Terms,
			&i.TermsVersion,
			&i.TermsHash,
			&i.Timezone,
			&i.StartsOn,
			&i.EndsOn,
			&i.OverridesUsed,
			&i.ScheduledAt,
			&i.SettledAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPactsForUserPage = `-- name: ListPactsForUserPage :many
select p.id, p.title, p.description, p.status, p.created_by, p.backer_id, p.terms, p.terms_version, p.terms_hash, p.timezone, p.starts_on, p.ends_on, p.overrides_used, p.scheduled_at, p.settled_at, p.completed_at, p.created_at, p.updated_at from pacts p
join pact_members m on m.pact_id = p.id and m.user_id = $1
where $2::timestamptz is null
   or (p.created_at, p.id) < ($2::timestamptz, $3::uuid)
order by p.created_at desc, p.id desc
limit $4
`

type ListPactsForUserPageParams struct {
	UserID   uuid.UUID
	BeforeAt *time.Time
	BeforeID *uuid.UUID
	MaxRows  int32
}

// Keyset page, newest first. The cursor is the last row's (created_at, id).
func (q *Queries) ListPactsForUserPage(ctx context.Context, arg ListPactsForUserPageParams) ([]Pact, error) {
	rows, err := q.db.Query(ctx, listPactsForUserPage,
		arg.UserID,
		arg.BeforeAt,
		arg.BeforeID,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Pact{}
	for rows.Next() {
		var i Pact
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.CreatedBy,
			&i.BackerID,
			&i.Terms,
			&i.TermsVersion,
			&i.TermsHash,
			&i.Timezone,
			&i.StartsOn,
			&i.EndsOn,
			&i.OverridesUsed,
			&i.ScheduledAt,
			&i.SettledAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSettlablePacts = `-- name: ListSettlablePacts :many
select p.id from pacts p
where p.status = 'active'
  and ($1::timestamptz at time zone p.timezone)::date > p.ends_on
  and not exists (select 1 from check_ins c where c.pact_id = p.id and not c.is_final)
order by p.ends_on
limit $2
`

type ListSettlablePactsParams struct {
	Now     time.Time
	MaxRows int32
}

// Active pacts past their end date whose every check-in is final (SPEC §7 step 7).
func (q *Queries) ListSettlablePacts(ctx context.Context, arg ListSettlablePactsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listSettlablePacts, arg.Now, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetAcceptances = `-- name: ResetAcceptances :exec
update pact_members
set accepted_terms_hash = null, accepted_at = null, signature_name = null
where pact_id = $1
`

func (q *Queries) ResetAcceptances(ctx context.Context, pactID uuid.UUID) error {
	_, err := q.db.Exec(ctx, resetAcceptances, pactID)
	return err
}

const setPactStatus = `-- name: SetPactStatus :execrows
update pacts
set status = $1, updated_at = now(),
    scheduled_at = case when $1::text = 'scheduled' then now() else scheduled_at end,
    settled_at   = case when $1::text = 'settling'  then now() else settled_at end,
    completed_at = case when $1::text = 'completed' then now() else completed_at end
where id = $2 and status = $3
`

type SetPactStatusParams struct {
	ToStatus   string
	ID         uuid.UUID
	FromStatus string
}

// Guarded status change: affects 0 rows when the pact is not in from_status.
func (q *Queries) SetPactStatus(ctx context.Context, arg SetPactStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, setPactStatus, arg.ToStatus, arg.ID, arg.FromStatus)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updatePactTerms = `-- name: UpdatePactTerms :execrows
update pacts
set title = $1, description = $2,
    terms = $3, terms_hash = $4, terms_version = terms_version + 1,
    timezone = $5, starts_on = $6, ends_on = $7,
    updated_at = now()
where id = $8 and status in ('draft', 'proposed')
`

type UpdatePactTermsParams struct {
	Title       string
	Description *string
	Terms       json.RawMessage
	TermsHash   string
	Timezone    string
	StartsOn    time.Time
	EndsOn      time.Time
	ID          uuid.UUID
}

// Terms can change only before both members accepted (SPEC §3).
func (q *Queries) UpdatePactTerms(ctx context.Context, arg UpdatePactTermsParams) (int64, error) {
	result, err := q.db.Exec(ctx, updatePactTerms,
		arg.Title,
		arg.Description,
		arg.Terms,
		arg.TermsHash,
		arg.Timezone,
		arg.StartsOn,
		arg.EndsOn,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const useInvite = `-- name: UseInvite :execrows
update pact_invites set used_at = now() where token_hash = $1 and used_at is null
`

// Expiry is checked by the service against its injected clock.
func (q *Queries) UseInvite(ctx context.Context, tokenHash string) (int64, error) {
	result, err := q.db.Exec(ctx, useInvite, tokenHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
