// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: proofs.sql

package store

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const attachToProof = `-- name: AttachToProof :execrows
update attachments set proof_id = $1
where id = any($2::uuid[]) and owner_id = $3 and pact_id = $4
`

type AttachToProofParams struct {
	ProofID *uuid.UUID
	Ids     []uuid.UUID
	OwnerID uuid.UUID
	PactID  uuid.UUID
}

func (q *Queries) AttachToProof(ctx context.Context, arg AttachToProofParams) (int64, error) {
	result, err := q.db.Exec(ctx, attachToProof,
		arg.ProofID,
		arg.Ids,
		arg.OwnerID,
		arg.PactID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countAttachmentsByStatus = `-- name: CountAttachmentsByStatus :many
select status, count(*)::int as n from attachments
where id = any($1::uuid[]) and owner_id = $2 and pact_id = $3
group by status
`

type CountAttachmentsByStatusParams struct {
	Ids     []uuid.UUID
	OwnerID uuid.UUID
	PactID  uuid.UUID
}

type CountAttachmentsByStatusRow struct {
	Status string
	N      int32
}

func (q *Queries) CountAttachmentsByStatus(ctx context.Context, arg CountAttachmentsByStatusParams) ([]CountAttachmentsByStatusRow, error) {
	rows, err := q.db.Query(ctx, countAttachmentsByStatus, arg.Ids, arg.OwnerID, arg.PactID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountAttachmentsByStatusRow{}
	for rows.Next() {
		var i CountAttachmentsByStatusRow
		if err := rows.Scan(&i.Status, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createAttachment = `-- name: CreateAttachment :one
insert into attachments (id, owner_id, pact_id, kind, declared_mime, declared_bytes, staging_key)
values ($1, $2, $3, $4, $5, $6, $7)
returning id, owner_id, pact_id, proof_id, kind, status, staging_key, media_key, thumb_key, declared_mime, sniffed_mime, declared_bytes, stored_bytes, width, height, duration_ms, reject_reason, created_at, ready_at
`

type CreateAttachmentParams struct {
	ID            uuid.UUID
	OwnerID       uuid.UUID
	PactID        uuid.UUID
	Kind          string
	DeclaredMime  *string
	DeclaredBytes *int64
	StagingKey    *string
}

func (q *Queries) CreateAttachment(ctx context.Context, arg CreateAttachmentParams) (Attachment, error) {
	row := q.db.QueryRow(ctx, createAttachment,
		arg.ID,
		arg.OwnerID,
		arg.PactID,
		arg.Kind,
		arg.DeclaredMime,
		arg.DeclaredBytes,
		arg.StagingKey,
	)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.PactID,
		&i.ProofID,
		&i.Kind,
		&i.Status,
		&i.StagingKey,
		&i.MediaKey,
		&i.ThumbKey,
		&i.DeclaredMime,
		&i.SniffedMime,
		&i.DeclaredBytes,
		&i.StoredBytes,
		&i.Width,
		&i.Height,
		&i.DurationMs,
		&i.RejectReason,
		&i.CreatedAt,
		&i.ReadyAt,
	)
	return i, err
}

const getAttachment = `-- name: GetAttachment :one
select id, owner_id, pact_id, proof_id, kind, status, staging_key, media_key, thumb_key, declared_mime, sniffed_mime, declared_bytes, stored_bytes, width, height, duration_ms, reject_reason, created_at, ready_at from attachments where id = $1
`

func (q *Queries) GetAttachment(ctx context.Context, id uuid.UUID) (Attachment, error) {
	row := q.db.QueryRow(ctx, getAttachment, id)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.PactID,
		&i.ProofID,
		&i.Kind,
		&i.Status,
		&i.StagingKey,
		&i.MediaKey,
		&i.ThumbKey,
		&i.DeclaredMime,
		&i.SniffedMime,
		&i.DeclaredBytes,
		&i.StoredBytes,
		&i.Width,
		&i.Height,
		&i.DurationMs,
		&i.RejectReason,
		&i.CreatedAt,
		&i.ReadyAt,
	)
	return i, err
}

const getLatestProof = `-- name: GetLatestProof :one
select id, check_in_id, version, body_doc, body_text, word_count, links, created_at from proofs where check_in_id = $1 order by version desc limit 1
`

func (q *Queries) GetLatestProof(ctx context.Context, checkInID uuid.UUID) (Proof, error) {
	row := q.db.QueryRow(ctx, getLatestProof, checkInID)
	var i Proof
	err := row.Scan(
		&i.ID,
		&i.CheckInID,
		&i.Version,
		&i.BodyDoc,
		&i.BodyText,
		&i.WordCount,
		&i.Links,
		&i.CreatedAt,
	)
	return i, err
}

const insertDecision = `-- name: InsertDecision :exec
insert into decisions (check_in_id, actor_id, action, reason) values ($1, $2, $3, $4)
`

type InsertDecisionParams struct {
	CheckInID uuid.UUID
	ActorID   *uuid.UUID
	Action    string
	Reason    *string
}

func (q *Queries) InsertDecision(ctx context.Context, arg InsertDecisionParams) error {
	_, err := q.db.Exec(ctx, insertDecision,
		arg.CheckInID,
		arg.ActorID,
		arg.Action,
		arg.Reason,
	)
	return err
}

const insertProof = `-- name: InsertProof :one
insert into proofs (id, check_in_id, version, body_doc, body_text, word_count, links)
values ($1, $2,
        (select coalesce(max(version), 0) + 1 from proofs where check_in_id = $2),
        $3, $4, $5, $6)
returning id, check_in_id, version, body_doc, body_text, word_count, links, created_at
`

type InsertProofParams struct {
	ID        uuid.UUID
	CheckInID uuid.UUID
	BodyDoc   json.RawMessage
	BodyText  string
	WordCount int32
	Links     json.RawMessage
}

func (q *Queries) InsertProof(ctx context.Context, arg InsertProofParams) (Proof, error) {
	row := q.db.QueryRow(ctx, insertProof,
		arg.ID,
		arg.CheckInID,
		arg.BodyDoc,
		arg.BodyText,
		arg.WordCount,
		arg.Links,
	)
	var i Proof
	err := row.Scan(
		&i.ID,
		&i.CheckInID,
		&i.Version,
		&i.BodyDoc,
		&i.BodyText,
		&i.WordCount,
		&i.Links,
		&i.CreatedAt,
	)
	return i, err
}

const listAttachmentsForProof = `-- name: ListAttachmentsForProof :many
select id, owner_id, pact_id, proof_id, kind, status, staging_key, media_key, thumb_key, declared_mime, sniffed_mime, declared_bytes, stored_bytes, width, height, duration_ms, reject_reason, created_at, ready_at from attachments where proof_id = $1 order by created_at
`

func (q *Queries) ListAttachmentsForProof(ctx context.Context, proofID *uuid.UUID) ([]Attachment, error) {
	rows, err := q.db.Query(ctx, listAttachmentsForProof, proofID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Attachment{}
	for rows.Next() {
		var i Attachment
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.PactID,
			&i.ProofID,
			&i.Kind,
			&i.Status,
			&i.StagingKey,
			&i.MediaKey,
			&i.ThumbKey,
			&i.DeclaredMime,
			&i.SniffedMime,
			&i.DeclaredBytes,
			&i.StoredBytes,
			&i.Width,
			&i.Height,
			&i.DurationMs,
			&i.RejectReason,
			&i.CreatedAt,
			&i.ReadyAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDecisions = `-- name: ListDecisions :many
select d.id, d.check_in_id, d.actor_id, d.action, d.reason, d.created_at, u.display_name as actor_name from decisions d
left join users u on u.id = d.actor_id
where d.check_in_id = $1
order by d.id
`

type ListDecisionsRow struct {
	ID        int64
	CheckInID uuid.UUID
	ActorID   *uuid.UUID
	Action    string
	Reason    *string
	CreatedAt time.Time
	ActorName *string
}

func (q *Queries) ListDecisions(ctx context.Context, checkInID uuid.UUID) ([]ListDecisionsRow, error) {
	rows, err := q.db.Query(ctx, listDecisions, checkInID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDecisionsRow{}
	for rows.Next() {
		var i ListDecisionsRow
		if err := rows.Scan(
			&i.ID,
			&i.CheckInID,
			&i.ActorID,
			&i.Action,
			&i.Reason,
			&i.CreatedAt,
			&i.ActorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProofs = `-- name: ListProofs :many
select id, check_in_id, version, body_doc, body_text, word_count, links, created_at from proofs where check_in_id = $1 order by version desc
`

func (q *Queries) ListProofs(ctx context.Context, checkInID uuid.UUID) ([]Proof, error) {
	rows, err := q.db.Query(ctx, listProofs, checkInID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Proof{}
	for rows.Next() {
		var i Proof
		if err := rows.Scan(
			&i.ID,
			&i.CheckInID,
			&i.Version,
			&i.BodyDoc,
			&i.BodyText,
			&i.WordCount,
			&i.Links,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
