// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

type Querier interface {
	AcceptTerms(ctx context.Context, arg AcceptTermsParams) (int64, error)
	ActivateDuePacts(ctx context.Context, now time.Time) ([]uuid.UUID, error)
	AddPactMember(ctx context.Context, arg AddPactMemberParams) error
	AttachToProof(ctx context.Context, arg AttachToProofParams) (int64, error)
	ConfirmPayout(ctx context.Context, pactID uuid.UUID) (int64, error)
	CountAcceptances(ctx context.Context, arg CountAcceptancesParams) (int64, error)
	CountAttachmentsByStatus(ctx context.Context, arg CountAttachmentsByStatusParams) ([]CountAttachmentsByStatusRow, error)
	CountCheckInsForPact(ctx context.Context, pactID uuid.UUID) (int64, error)
	CountNonFinalCheckIns(ctx context.Context, pactID uuid.UUID) (int64, error)
	CountOpenPactsForUser(ctx context.Context, userID uuid.UUID) (int64, error)
	CountReviewQueue(ctx context.Context, reviewerID uuid.UUID) (int64, error)
	CountUnreadNotifications(ctx context.Context, userID uuid.UUID) (int64, error)
	CreateAttachment(ctx context.Context, arg CreateAttachmentParams) (Attachment, error)
	CreateInvite(ctx context.Context, arg CreateInviteParams) error
	CreatePact(ctx context.Context, arg CreatePactParams) (Pact, error)
	CreatePayout(ctx context.Context, arg CreatePayoutParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	FetchPendingOutbox(ctx context.Context, limit int32) ([]Outbox, error)
	GetAttachment(ctx context.Context, id uuid.UUID) (Attachment, error)
	GetCheckIn(ctx context.Context, id uuid.UUID) (CheckIn, error)
	GetCheckInForMember(ctx context.Context, arg GetCheckInForMemberParams) (CheckIn, error)
	GetCheckInForUpdate(ctx context.Context, id uuid.UUID) (CheckIn, error)
	// Used by settlement: another worker holding the row means it is being handled.
	GetCheckInForUpdateSkipLocked(ctx context.Context, id uuid.UUID) (CheckIn, error)
	GetInvite(ctx context.Context, tokenHash string) (PactInvite, error)
	GetLatestProof(ctx context.Context, checkInID uuid.UUID) (Proof, error)
	GetLedgerEntryByKey(ctx context.Context, idempotencyKey string) (LedgerEntry, error)
	GetPact(ctx context.Context, id uuid.UUID) (Pact, error)
	// Membership-filtered read (AGENTS.md invariant 8): no row for non-members.
	GetPactForMember(ctx context.Context, arg GetPactForMemberParams) (Pact, error)
	// Locks the pact row: serialises ledger clamps and counters for one pact (ADR-0002).
	GetPactForUpdate(ctx context.Context, id uuid.UUID) (Pact, error)
	GetPactMember(ctx context.Context, arg GetPactMemberParams) (PactMember, error)
	GetPayout(ctx context.Context, pactID uuid.UUID) (Payout, error)
	GetUser(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	IncrementOverridesUsed(ctx context.Context, id uuid.UUID) error
	IncrementRestDaysUsed(ctx context.Context, arg IncrementRestDaysUsedParams) error
	InsertCheckIns(ctx context.Context, arg []InsertCheckInsParams) (int64, error)
	InsertDecision(ctx context.Context, arg InsertDecisionParams) error
	// Idempotent insert: returns no row (pgx.ErrNoRows) when the key already exists (SPEC §6 L3).
	InsertLedgerEntry(ctx context.Context, arg InsertLedgerEntryParams) (LedgerEntry, error)
	InsertNotification(ctx context.Context, arg InsertNotificationParams) error
	InsertOutbox(ctx context.Context, arg InsertOutboxParams) error
	InsertProof(ctx context.Context, arg InsertProofParams) (Proof, error)
	// 0 rows = this reminder was already sent (possibly by another worker).
	InsertReminderSent(ctx context.Context, arg InsertReminderSentParams) (int64, error)
	ListAttachmentsForProof(ctx context.Context, proofID *uuid.UUID) ([]Attachment, error)
	ListCheckInsForPact(ctx context.Context, arg ListCheckInsForPactParams) ([]CheckIn, error)
	// Reminders (SPEC §9). Open check-ins of active pacts whose cutoff falls in (from_at, to_at]
	// and that were not yet reminded with this kind.
	ListCutoffReminderCandidates(ctx context.Context, arg ListCutoffReminderCandidatesParams) ([]CheckIn, error)
	ListDecisions(ctx context.Context, checkInID uuid.UUID) ([]ListDecisionsRow, error)
	// Every check-in with a passed deadline, oldest deadline first (SPEC §7 steps 1-5).
	ListDueCheckInIDs(ctx context.Context, arg ListDueCheckInIDsParams) ([]uuid.UUID, error)
	// Passbook page, newest first, with the running balance after each line. The window
	// runs over the whole pact ledger before the cursor filter, so every page agrees.
	// The check-in join only adds the day and member a line is about.
	ListLedgerPage(ctx context.Context, arg ListLedgerPageParams) ([]ListLedgerPageRow, error)
	ListMembersForPacts(ctx context.Context, pactIds []uuid.UUID) ([]ListMembersForPactsRow, error)
	ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]Notification, error)
	ListPactMembers(ctx context.Context, pactID uuid.UUID) ([]ListPactMembersRow, error)
	ListPactsForUser(ctx context.Context, userID uuid.UUID) ([]Pact, error)
	// Keyset page, newest first. The cursor is the last row's (created_at, id).
	ListPactsForUserPage(ctx context.Context, arg ListPactsForUserPageParams) ([]Pact, error)
	ListPayoutsForPacts(ctx context.Context, pactIds []uuid.UUID) ([]Payout, error)
	ListProofs(ctx context.Context, checkInID uuid.UUID) ([]Proof, error)
	// Keyset page ordered by (review_deadline, id), soonest first. The proof word count and
	// attachment count come from the latest proof version.
	ListReviewQueuePage(ctx context.Context, arg ListReviewQueuePageParams) ([]ListReviewQueuePageRow, error)
	// Submitted check-ins whose review deadline falls in (from_at, to_at] and whose reviewer
	// was not yet reminded.
	ListReviewReminderCandidates(ctx context.Context, arg ListReviewReminderCandidatesParams) ([]CheckIn, error)
	// Active pacts past their end date whose every check-in is final (SPEC §7 step 7).
	ListSettlablePacts(ctx context.Context, arg ListSettlablePactsParams) ([]uuid.UUID, error)
	// My check-ins for the Today screen: dated today in each active pact's timezone, plus an
	// earlier day that is still open because its grace period has not ended.
	ListTodayCheckIns(ctx context.Context, arg ListTodayCheckInsParams) ([]ListTodayCheckInsRow, error)
	MarkNotificationsRead(ctx context.Context, arg MarkNotificationsReadParams) error
	MarkOutboxDispatched(ctx context.Context, ids []int64) error
	MarkPayoutPaid(ctx context.Context, arg MarkPayoutPaidParams) (int64, error)
	// My nearest unfinished deadline per pact (open days only).
	NextDeadlines(ctx context.Context, arg NextDeadlinesParams) ([]NextDeadlinesRow, error)
	// Pot balance is always the sum of the ledger (SPEC §6 L1).
	PotBalance(ctx context.Context, pactID uuid.UUID) (int64, error)
	// Balances for several pacts at once (list and Today screens).
	PotBalances(ctx context.Context, pactIds []uuid.UUID) ([]PotBalancesRow, error)
	ResetAcceptances(ctx context.Context, pactID uuid.UUID) error
	// Guarded status change: affects 0 rows when the pact is not in from_status.
	SetPactStatus(ctx context.Context, arg SetPactStatusParams) (int64, error)
	// Writes every mutable field, guarded by the status the transition started from
	// (optimistic check, SPEC §7). 0 rows = someone else moved it first.
	UpdateCheckInState(ctx context.Context, arg UpdateCheckInStateParams) (int64, error)
	// Terms can change only before both members accepted (SPEC §3).
	UpdatePactTerms(ctx context.Context, arg UpdatePactTermsParams) (int64, error)
	// Expiry is checked by the service against its injected clock.
	UseInvite(ctx context.Context, tokenHash string) (int64, error)
}

var _ Querier = (*Queries)(nil)
