// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
insert into users (id, email, password_hash, display_name, locale, timezone)
values ($1, $2, $3, $4, $5, $6)
returning id, email, password_hash, display_name, locale, timezone, avatar_key, email_verified_at, created_at
`

type CreateUserParams struct {
	ID           uuid.UUID
	Email        string
	PasswordHash string
	DisplayName  string
	Locale       string
	Timezone     string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.PasswordHash,
		arg.DisplayName,
		arg.Locale,
		arg.Timezone,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Locale,
		&i.Timezone,
		&i.AvatarKey,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
select id, email, password_hash, display_name, locale, timezone, avatar_key, email_verified_at, created_at from users where id = $1
`

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Locale,
		&i.Timezone,
		&i.AvatarKey,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
select id, email, password_hash, display_name, locale, timezone, avatar_key, email_verified_at, created_at from users where email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Locale,
		&i.Timezone,
		&i.AvatarKey,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
	)
	return i, err
}
