/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create an account and start a session
         * @description Sets the `tepati_session` and `tepati_csrf` cookies on success.
         */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start a session
         * @description Sets the `tepati_session` and `tepati_csrf` cookies on success. Limited to 10 attempts per
         *     minute per IP and per email. A wrong email and a wrong password are indistinguishable.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * End the session
         * @description Deletes the server-side session and clears both cookies. Safe to call twice.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The signed-in user */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Change my name, language, time zone or which emails I get
         * @description Only the fields that are sent change. The name is also the signature typed when accepting
         *     terms; signatures already given keep the name that was typed then. `email_kinds_off` replaces
         *     the whole list. Only the kinds in `EmailKind` can be switched off (SPEC §9): invites, a
         *     dispute opened against you and a settled pact are always mailed, and the in-app inbox is
         *     never switched off.
         */
        patch: operations["updateMe"];
        trace?: never;
    };
    "/me/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Change my password
         * @description Needs the current password. On success every other session of this user is ended and this
         *     one stays signed in. Wrong attempts are limited per user (`auth.rate_limited`), so a stolen
         *     session cannot be used to guess the current password.
         */
        post: operations["changePassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/today": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Everything the Today screen needs, in one call
         * @description My check-ins for today and any still-open earlier ones, how many submissions wait for my
         *     review, and a pot summary per active pact (ordered by the nearest deadline).
         */
        get: operations["getToday"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * My pacts
         * @description Newest first. Includes pacts in every status, so the client can filter.
         */
        get: operations["listPacts"];
        put?: never;
        /**
         * Create a draft pact
         * @description The creator is always the backer (SPEC §2). The doer's terms are keyed by the nil UUID
         *     (`00000000-0000-0000-0000-000000000000`) until the invitee joins.
         */
        post: operations["createPact"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pacts/{pactId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pactId: components["parameters"]["PactId"];
            };
            cookie?: never;
        };
        /** Pact detail */
        get: operations["getPact"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Edit title, description and terms
         * @description Only in `draft` or `proposed`. The body replaces the title, description and terms. Any
         *     change to the terms bumps `terms_version`, recomputes `terms_hash` and clears both
         *     signatures, and the other member is notified.
         */
        patch: operations["updatePact"];
        trace?: never;
    };
    "/pacts/{pactId}/propose": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pactId: components["parameters"]["PactId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Move a draft to proposed and create an invite
         * @description Backer only. Callable again while `proposed` to mint a fresh invite link. Only the hash of
         *     the token is stored, so the token is shown exactly once, in this response.
         */
        post: operations["proposePact"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pacts/{pactId}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pactId: components["parameters"]["PactId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign the current terms
         * @description Valid only for the exact `terms_hash` the member read, and only if `signature_name` equals
         *     their display name. Accepting twice is a no-op. When both members have signed the same
         *     hash, the pact becomes `scheduled`, the pot is funded and every check-in is generated.
         */
        post: operations["acceptPact"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/invites/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The one-time invite token from `proposePact`. */
                token: components["parameters"]["InviteToken"];
            };
            cookie?: never;
        };
        /**
         * Preview the terms behind an invite link
         * @description Public, because the invitee may not have an account yet. The token is the credential.
         *     It reveals only what the invitee needs to decide: the terms and who invited them.
         */
        get: operations["previewInvite"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/invites/{token}/join": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The one-time invite token from `proposePact`. */
                token: components["parameters"]["InviteToken"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Take the doer slot of an invited pact
         * @description Added because accepting needs membership (`ARCHITECTURE §5` had no way in). The caller
         *     becomes the doer, the invite is consumed, and the doer slot in the terms is re-keyed to the
         *     caller. That changes `terms_hash`, so any earlier signature is cleared and the caller must
         *     then call `acceptPact` with the new hash.
         */
        post: operations["joinInvite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pacts/{pactId}/check-ins": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pactId: components["parameters"]["PactId"];
            };
            cookie?: never;
        };
        /**
         * Check-ins of a pact, for the calendar
         * @description Both members' check-ins, ordered by `local_date` then member. Bounded by the pact length, so there is no cursor.
         */
        get: operations["listPactCheckIns"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/check-ins/{checkInId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                checkInId: components["parameters"]["CheckInId"];
            };
            cookie?: never;
        };
        /**
         * Check-in detail
         * @description The latest proof, the version history, attachments, the full decision timeline and the
         *     actions the caller may take right now (`my_actions`), so the client never re-derives the
         *     state machine.
         */
        get: operations["getCheckIn"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/check-ins/{checkInId}/proof": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                checkInId: components["parameters"]["CheckInId"];
            };
            cookie?: never;
        };
        get?: never;
        /**
         * Submit or replace the proof
         * @description Creates a new proof version and submits (or re-submits) the check-in. Allowed until
         *     `submit_deadline`. The server validates `body_doc` against the allow-list in SPEC §8, derives
         *     the text and word count, and checks the evidence rules and that every attachment is `ready`.
         */
        put: operations["submitProof"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/check-ins/{checkInId}/rest": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                checkInId: components["parameters"]["CheckInId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Declare a rest day
         * @description Only for an `open` check-in and before the cutoff, up to the pact's `rest_days`. Never retroactive.
         */
        post: operations["declareRest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/check-ins/{checkInId}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                checkInId: components["parameters"]["CheckInId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve a submission
         * @description Reviewer only. Nobody reviews their own check-in.
         */
        post: operations["approveCheckIn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/check-ins/{checkInId}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                checkInId: components["parameters"]["CheckInId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reject a submission
         * @description Reviewer only. A written reason of at least 10 characters is required. The doer may dispute within the dispute window.
         */
        post: operations["rejectCheckIn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/check-ins/{checkInId}/override": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                checkInId: components["parameters"]["CheckInId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Override an auto-approval (backer power)
         * @description Backer only, and only on a check-in the backer reviews. Turns an `auto_approved` check-in
         *     into a final `rejected` one within `override_window_hours`, at most `max_overrides` times
         *     per pact. The doer cannot dispute it. Always writes a visible decision.
         */
        post: operations["overrideCheckIn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/check-ins/{checkInId}/dispute": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                checkInId: components["parameters"]["CheckInId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Dispute a rejection
         * @description Doer only, within the dispute window. A reason is required. A pending dispute moves no coins.
         */
        post: operations["disputeCheckIn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/check-ins/{checkInId}/dispute/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                checkInId: components["parameters"]["CheckInId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resolve a dispute (backer power)
         * @description Backer only, and only on a check-in the backer reviewed. `uphold` approves the check-in and
         *     `dismiss` makes the rejection final. Both need a written rationale (SPEC §2). If nobody
         *     resolves it before `resolution_deadline`, the system approves it.
         */
        post: operations["resolveDispute"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/review-queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Submissions waiting for my review
         * @description Check-ins in `submitted` where I am the reviewer, soonest `review_deadline` first.
         */
        get: operations["getReviewQueue"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pacts/{pactId}/ledger": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pactId: components["parameters"]["PactId"];
            };
            cookie?: never;
        };
        /**
         * Passbook lines with a running balance
         * @description Newest first. `balance_after` is the pot after that line, computed with a window function
         *     over the whole ledger, so it stays correct on every page. The pot balance is always
         *     `SUM(amount)`. There is no stored balance.
         */
        get: operations["listLedger"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pacts/{pactId}/payout/mark-paid": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pactId: components["parameters"]["PactId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * The backer says the IOU was paid
         * @description Backer only, while the pact is `settling`. Repeating it is a no-op.
         */
        post: operations["markPayoutPaid"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pacts/{pactId}/payout/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pactId: components["parameters"]["PactId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * The doer confirms receipt
         * @description Doer only, while the pact is `settling`. The doer's confirmation alone completes the pact
         *     (SPEC §3), whether or not the backer marked it paid.
         */
        post: operations["confirmPayout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ask for an upload slot
         * @description Validates the declared kind, type and size against the limits (SPEC §8) and the per-pact
         *     quota, then returns a presigned PUT. The bytes go straight to object storage and never
         *     through the API. Limited to 30 intents per minute. Returns `503` with `Retry-After` when
         *     the media queue is full.
         */
        post: operations["createUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/uploads/{attachmentId}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attachmentId: components["parameters"]["AttachmentId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * The PUT finished; start processing
         * @description The server HEADs the object and rejects a size that differs from the declared one, then
         *     queues processing. Poll `getAttachment` until the status is `ready` or `rejected`.
         */
        post: operations["completeUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/attachments/{attachmentId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attachmentId: components["parameters"]["AttachmentId"];
            };
            cookie?: never;
        };
        /**
         * Attachment status and signed URLs
         * @description Visible to the pact's members only. When `ready`, `urls` holds signed GET URLs valid for
         *     5 minutes. Fetch them again when they expire. Buckets are never public.
         */
        get: operations["getAttachment"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * My inbox
         * @description Newest first.
         */
        get: operations["listNotifications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mark notifications as read
         * @description Ids that are already read, or that belong to someone else, are ignored.
         */
        post: operations["markNotificationsRead"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness
         * @description The process is up. Does not touch dependencies.
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness
         * @description Pings Postgres, Redis and object storage. Returns `503` if any is down.
         */
        get: operations["getReadiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Stable machine-readable error code. The web app maps each one to an i18n message.
         *
         *     | Status | Codes |
         *     |---|---|
         *     | 400 | `validation.failed`, `auth.invalid_email`, `auth.invalid_name`, `auth.weak_password`, `auth.wrong_password`, `pact.invalid_terms`, `pact.terms_members`, `proof.invalid_doc`, `checkin.reason_required`, `upload.size_mismatch` |
         *     | 401 | `auth.unauthenticated`, `auth.invalid_credentials` |
         *     | 403 | `auth.csrf`, `pact.not_backer`, `pact.not_doer`, `checkin.not_allowed` |
         *     | 404 | `not_found` (also for non-members) |
         *     | 405 | `method_not_allowed` |
         *     | 409 | `auth.email_taken`, `pact.invalid_state`, `pact.terms_mismatch`, `pact.member_missing`, `pact.start_passed`, `pact.limit_reached`, `checkin.invalid_transition`, `checkin.conflict`, `checkin.override_limit`, `checkin.rest_limit`, `upload.quota_exceeded`, `idempotency.in_progress` |
         *     | 410 | `pact.invite_invalid` |
         *     | 413 | `upload.too_large`, `request.too_large` |
         *     | 415 | `upload.unsupported_type`, `request.unsupported_media_type` |
         *     | 422 | `pact.signature_mismatch`, `checkin.deadline_passed`, `checkin.evidence_insufficient`, `idempotency.key_reused` |
         *     | 429 | `rate_limited`, `auth.rate_limited` |
         *     | 500 | `server.internal` |
         *     | 503 | `upload.queue_busy`, `server.unavailable` |
         * @enum {string}
         */
        ErrorCode: "validation.failed" | "not_found" | "method_not_allowed" | "request.too_large" | "request.unsupported_media_type" | "rate_limited" | "server.internal" | "server.unavailable" | "idempotency.in_progress" | "idempotency.key_reused" | "auth.unauthenticated" | "auth.csrf" | "auth.invalid_credentials" | "auth.email_taken" | "auth.invalid_email" | "auth.invalid_name" | "auth.weak_password" | "auth.wrong_password" | "auth.rate_limited" | "pact.invalid_state" | "pact.invalid_terms" | "pact.terms_members" | "pact.terms_mismatch" | "pact.not_backer" | "pact.not_doer" | "pact.invite_invalid" | "pact.limit_reached" | "pact.start_passed" | "pact.signature_mismatch" | "pact.member_missing" | "proof.invalid_doc" | "checkin.invalid_transition" | "checkin.not_allowed" | "checkin.deadline_passed" | "checkin.reason_required" | "checkin.evidence_insufficient" | "checkin.override_limit" | "checkin.rest_limit" | "checkin.conflict" | "upload.too_large" | "upload.unsupported_type" | "upload.size_mismatch" | "upload.quota_exceeded" | "upload.queue_busy";
        FieldError: {
            /** @description JSON path of the offending field, for example `terms.members.<id>.penalty_per_miss`. */
            field: string;
            message: string;
        };
        /** @description RFC 9457 problem details with a stable `code`. */
        Problem: {
            /**
             * @description A URI naming the problem type. `about:blank` when `code` says it all.
             * @default about:blank
             */
            type: string;
            /** @description A short English summary. Not for display. */
            title: string;
            status: number;
            detail?: string | null;
            instance?: string | null;
            code: components["schemas"]["ErrorCode"];
            /** @description Echo of the `X-Request-Id` header, for support. */
            request_id?: string | null;
            /** @description Per-field detail, present for `validation.failed` and `pact.invalid_terms`. */
            errors?: components["schemas"]["FieldError"][];
        };
        User: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            display_name: string;
            /** @enum {string} */
            locale: "id" | "en";
            /**
             * @description IANA zone
             * @example Asia/Jakarta
             */
            timezone: string;
            /** @description The kinds of email this person has switched off, sorted. Empty means every email is on. */
            email_kinds_off: components["schemas"]["EmailKind"][];
            /** Format: date-time */
            created_at: string;
        };
        ChangePasswordRequest: {
            /** Format: password */
            current_password: string;
            /** Format: password */
            new_password: string;
        };
        /**
         * @description A kind of notification email that can be switched off.
         * @enum {string}
         */
        EmailKind: "terms_changed" | "terms_signed" | "proof_submitted" | "proof_rejected" | "proof_overridden" | "proof_auto_approved";
        UpdateMeRequest: {
            display_name?: string;
            /** @enum {string} */
            locale?: "id" | "en";
            /** @description IANA zone. */
            timezone?: string;
            email_kinds_off?: components["schemas"]["EmailKind"][];
        };
        RegisterRequest: {
            /** Format: email */
            email: string;
            /** Format: password */
            password: string;
            /** @description Also the signature the user types when accepting terms. */
            display_name: string;
            /**
             * @default id
             * @enum {string}
             */
            locale: "id" | "en";
            /**
             * @description IANA zone.
             * @default Asia/Jakarta
             */
            timezone: string;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            /** Format: password */
            password: string;
        };
        /** @description Just enough about a member to draw a line in their colour. */
        MemberRef: {
            /** Format: uuid */
            user_id: string;
            display_name: string;
            line_color: components["schemas"]["LineColor"];
        };
        /** @description The member's fixed colour for the whole pact. */
        LineColor: string;
        /**
         * @description The frozen rule set both members sign (SPEC §4). `terms_hash` is sha256 of its canonical JSON.
         *     The server validates every rule and answers `pact.invalid_terms` with per-field `errors`.
         */
        Terms: {
            /** @description Schema version of the terms document. */
            version: number;
            /**
             * @description IANA zone
             * @example Asia/Jakarta
             */
            timezone: string;
            /** Format: date */
            starts_on: string;
            /**
             * Format: date
             * @description Between 1 and 366 days after `starts_on`.
             */
            ends_on: string;
            /** @example 23:59 */
            cutoff_local_time: string;
            grace_minutes: number;
            /**
             * Format: int64
             * @description Rupiah per coin. Display only, since the ledger is an IOU.
             */
            coin_rate_idr: number;
            /** Format: int64 */
            initial_pot: number;
            /**
             * Format: int64
             * @description The pot never drops below this.
             */
            pot_floor: number;
            /**
             * Format: int64
             * @description Backer bonuses stop at this. `null` means no cap. Must be at least `initial_pot`.
             */
            pot_cap: number | null;
            review_window_hours: number;
            dispute_window_hours: number;
            dispute_resolution_hours: number;
            override_window_hours: number;
            /** @description 0 disables the override power. */
            max_overrides: number;
            /** @description Whether the backer also has a daily commitment. */
            backer_commits: boolean;
            /**
             * @description Keyed by user id. Exactly the backer and one doer. Until the invitee joins, the doer
             *     slot is keyed by the nil UUID `00000000-0000-0000-0000-000000000000`.
             */
            members: {
                [key: string]: components["schemas"]["MemberTerms"];
            };
        };
        MemberTerms: {
            /** @enum {string} */
            role: "backer" | "doer";
            /** @description Shown to the member every day. */
            commitment: string;
            /** @description ISO weekdays, 1 = Monday. Empty means this member does not commit (backer only). */
            schedule: number[];
            /**
             * Format: int64
             * @description Coins taken from the pot when a doer misses, or added to it when the backer misses.
             */
            penalty_per_miss: number;
            /** @description Rest days this member may declare in the pact. */
            rest_days: number;
            evidence: components["schemas"]["Evidence"];
        };
        Evidence: {
            min_attachments: number;
            min_words: number;
        };
        /** @enum {string} */
        PactStatus: "draft" | "proposed" | "scheduled" | "active" | "settling" | "completed" | "cancelled";
        /** @enum {string} */
        Role: "backer" | "doer";
        PactDraft: {
            title: string;
            description?: string | null;
            terms: components["schemas"]["Terms"];
        };
        PactMember: {
            /** Format: uuid */
            user_id: string;
            display_name: string;
            role: components["schemas"]["Role"];
            line_color: components["schemas"]["LineColor"];
            /** @description True only if they signed the *current* `terms_hash`. Editing the terms makes it false for both. */
            accepted: boolean;
            /** Format: date-time */
            accepted_at?: string | null;
            signature_name?: string | null;
            rest_days_used: number;
        };
        Pact: {
            /** Format: uuid */
            id: string;
            title: string;
            description?: string | null;
            status: components["schemas"]["PactStatus"];
            /** Format: uuid */
            backer_id: string;
            my_role: components["schemas"]["Role"];
            terms: components["schemas"]["Terms"];
            terms_version: number;
            terms_hash: string;
            timezone: string;
            /** Format: date */
            starts_on: string;
            /** Format: date */
            ends_on: string;
            overrides_used: number;
            /**
             * Format: int64
             * @description The pot, computed as the sum of the ledger. `0` before the pact is scheduled.
             */
            balance: number;
            /** @description The backer first. Only the backer until the doer joins. */
            members: components["schemas"]["PactMember"][];
            /** @description Present once the pact is `settling` or `completed`. */
            payout?: components["schemas"]["Payout"] | null;
            /** Format: date-time */
            scheduled_at?: string | null;
            /** Format: date-time */
            settled_at?: string | null;
            /** Format: date-time */
            completed_at?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        PactPage: {
            items: components["schemas"]["Pact"][];
            next_cursor: string | null;
        };
        ProposeRequest: {
            /**
             * Format: email
             * @description Optional. Locks the invite to this address and emails the link.
             */
            email?: string | null;
        };
        Proposal: {
            /** @description Shown once. Build the link as `{origin}/invite/{invite_token}`. It is valid for 7 days. */
            invite_token: string;
        };
        AcceptRequest: {
            /** @description The hash of the terms the member just read. A stale hash fails with `pact.terms_mismatch`. */
            terms_hash: string;
            /** @description Must equal the member's display name (case-insensitive, trimmed). */
            signature_name: string;
        };
        InvitePreview: {
            pact_title: string;
            inviter: components["schemas"]["MemberRef"];
            terms: components["schemas"]["Terms"];
            terms_hash: string;
            status: components["schemas"]["PactStatus"];
            /** @description False if someone already joined. */
            doer_slot_open: boolean;
        };
        /** @enum {string} */
        CheckInStatus: "open" | "submitted" | "approved" | "auto_approved" | "rejected" | "disputed" | "missed" | "rest";
        CheckIn: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            pact_id: string;
            /**
             * Format: uuid
             * @description The member who owes this check-in.
             */
            member_id: string;
            /**
             * Format: uuid
             * @description Always the other member.
             */
            reviewer_id: string;
            /**
             * Format: date
             * @description The day, in the pact timezone.
             */
            local_date: string;
            status: components["schemas"]["CheckInStatus"];
            is_final: boolean;
            /** Format: date-time */
            cutoff_at: string;
            /**
             * Format: date-time
             * @description Cutoff plus grace.
             */
            submit_deadline: string;
            /** Format: date-time */
            submitted_at?: string | null;
            /** Format: date-time */
            review_deadline?: string | null;
            /** Format: date-time */
            decided_at?: string | null;
            /** Format: date-time */
            dispute_deadline?: string | null;
            /** Format: date-time */
            disputed_at?: string | null;
            /** Format: date-time */
            resolution_deadline?: string | null;
            /** Format: date-time */
            override_deadline?: string | null;
            /** @description Whether coins moved because of this check-in. */
            penalty_applied: boolean;
        };
        CheckInList: {
            items: components["schemas"]["CheckIn"][];
        };
        /**
         * @description What the caller may do right now, derived on the server from the state machine and the deadlines.
         * @enum {string}
         */
        CheckInAction: "submit" | "edit_proof" | "declare_rest" | "approve" | "reject" | "override" | "dispute" | "resolve_dispute";
        CheckInDetail: {
            check_in: components["schemas"]["CheckIn"];
            pact_title: string;
            member: components["schemas"]["MemberRef"];
            reviewer: components["schemas"]["MemberRef"];
            /** @description The latest version. `null` until something was submitted. */
            proof?: components["schemas"]["Proof"] | null;
            /** @description Every version, oldest first, so the reviewer can see an edit happened. */
            proof_versions: components["schemas"]["ProofVersion"][];
            /** @description Attachments of the latest proof. */
            attachments: components["schemas"]["Attachment"][];
            /** @description Every decision row, oldest first. Power actions are visible to both members. */
            decisions: components["schemas"]["Decision"][];
            my_actions: components["schemas"]["CheckInAction"][];
            /** @description Backer's remaining overrides in the pact. `null` for anyone else. */
            overrides_remaining?: number | null;
        };
        Proof: {
            /** Format: uuid */
            id: string;
            version: number;
            /** @description Tiptap/ProseMirror JSON limited to the node and mark allow-list in SPEC §8. */
            body_doc: {
                [key: string]: unknown;
            };
            /** @description Plain text derived on the server. */
            body_text: string;
            word_count: number;
            links: string[];
            attachment_ids: string[];
            /** Format: date-time */
            created_at: string;
        };
        ProofVersion: {
            /** Format: uuid */
            id: string;
            version: number;
            word_count: number;
            /** Format: date-time */
            created_at: string;
        };
        ProofRequest: {
            /** @description Tiptap JSON. Anything outside the SPEC §8 allow-list fails with `proof.invalid_doc`. */
            body_doc: {
                [key: string]: unknown;
            };
            links?: string[];
            /** @description Attachments in the tray. Inline images are added automatically. They must be the caller's and all `ready`. */
            attachment_ids?: string[];
        };
        /** @enum {string} */
        DecisionAction: "submit" | "approve" | "reject" | "auto_approve" | "override" | "dispute" | "uphold" | "dismiss" | "dispute_expired" | "rest" | "missed" | "finalize";
        Decision: {
            /** Format: int64 */
            id: number;
            action: components["schemas"]["DecisionAction"];
            /**
             * Format: uuid
             * @description `null` means the system.
             */
            actor_id?: string | null;
            reason?: string | null;
            /** @description True for the backer's extra powers (`override`, `uphold`, `dismiss`). The UI draws these in stamp violet. */
            is_power: boolean;
            /** Format: date-time */
            created_at: string;
        };
        ReasonRequest: {
            /** @description At least 10 characters after trimming, counted in characters, not bytes. */
            reason: string;
        };
        ResolveDisputeRequest: {
            /**
             * @description `uphold` approves the check-in. `dismiss` makes the rejection final.
             * @enum {string}
             */
            outcome: "uphold" | "dismiss";
            /** @description The backer's rationale (SPEC §2). Both members see it. */
            reason: string;
        };
        ReviewQueueItem: {
            check_in: components["schemas"]["CheckIn"];
            pact_title: string;
            member: components["schemas"]["MemberRef"];
            word_count: number;
            attachment_count: number;
        };
        ReviewQueuePage: {
            items: components["schemas"]["ReviewQueueItem"][];
            next_cursor: string | null;
        };
        TodayCheckIn: {
            check_in: components["schemas"]["CheckIn"];
            pact_title: string;
            member: components["schemas"]["MemberRef"];
            /** @description Of the latest proof, if any. */
            word_count?: number | null;
        };
        TodayPact: {
            /** Format: uuid */
            pact_id: string;
            title: string;
            status: components["schemas"]["PactStatus"];
            my_role: components["schemas"]["Role"];
            /** Format: int64 */
            balance: number;
            partner: components["schemas"]["MemberRef"];
            /**
             * Format: date-time
             * @description My nearest unfinished deadline in this pact. Sections are ordered by it.
             */
            next_deadline?: string | null;
            /** @description The last three passbook lines, newest first, for the mini passbook. */
            recent_ledger: components["schemas"]["LedgerLine"][];
        };
        Today: {
            /**
             * Format: date-time
             * @description Lets the client correct its clock before it draws countdowns.
             */
            server_time: string;
            /** @description My check-ins dated today in each active pact's timezone, plus any earlier ones still open. Soonest `submit_deadline` first. */
            my_check_ins: components["schemas"]["TodayCheckIn"][];
            review_queue_count: number;
            /** @description Active pacts (and those `settling`), nearest `next_deadline` first. */
            pacts: components["schemas"]["TodayPact"][];
        };
        /** @enum {string} */
        LedgerKind: "pot_initial" | "doer_miss" | "backer_miss" | "reversal" | "payout";
        LedgerLine: {
            /** Format: int64 */
            id: number;
            kind: components["schemas"]["LedgerKind"];
            /**
             * Format: int64
             * @description Signed coins. Negative is a debit (D), positive a credit (K). A clamped penalty is `0` with `note = clamped`.
             */
            amount: number;
            /**
             * Format: int64
             * @description The pot after this line.
             */
            balance_after: number;
            /** Format: uuid */
            check_in_id?: string | null;
            /**
             * Format: date
             * @description The day this line is about, for the *keterangan* column.
             */
            check_in_local_date?: string | null;
            /**
             * Format: uuid
             * @description Whose check-in caused it, for the line colour.
             */
            member_id?: string | null;
            note?: string | null;
            /** Format: date-time */
            created_at: string;
        };
        LedgerPage: {
            items: components["schemas"]["LedgerLine"][];
            next_cursor: string | null;
            /**
             * Format: int64
             * @description The current pot, the same on every page.
             */
            balance: number;
        };
        Payout: {
            /**
             * Format: int64
             * @description Coins the backer owes the doer, fixed when the pact reached `settling`.
             */
            amount: number;
            /** Format: date-time */
            marked_paid_at?: string | null;
            marked_paid_note?: string | null;
            /** Format: date-time */
            confirmed_at?: string | null;
        };
        MarkPaidRequest: {
            /** @description For example how it was paid. */
            note?: string | null;
        };
        /** @enum {string} */
        AttachmentKind: "image" | "video" | "file";
        /** @enum {string} */
        AttachmentStatus: "awaiting_upload" | "uploaded" | "processing" | "ready" | "rejected";
        UploadIntentRequest: {
            /** Format: uuid */
            pact_id: string;
            kind: components["schemas"]["AttachmentKind"];
            /** @description Declared by the client for the pre-check only. The server sniffs the real type. */
            mime: string;
            /**
             * Format: int64
             * @description Exact size of the file about to be sent.
             */
            bytes: number;
        };
        UploadIntent: {
            /** Format: uuid */
            attachment_id: string;
            /**
             * Format: uri
             * @description Presigned PUT to object storage. Valid for 10 minutes.
             */
            put_url: string;
            /** @description Headers to send unchanged with the PUT, including the signed `Content-Length` and `Content-Type`. */
            headers: {
                [key: string]: string;
            };
            /** Format: date-time */
            expires_at: string;
        };
        AttachmentUrls: {
            /** Format: uri */
            original?: string;
            /** Format: uri */
            thumb?: string | null;
            /**
             * Format: uri
             * @description First frame of a video.
             */
            poster?: string | null;
            /**
             * Format: date-time
             * @description About 5 minutes after the response.
             */
            expires_at: string;
        };
        Attachment: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            pact_id: string;
            kind: components["schemas"]["AttachmentKind"];
            status: components["schemas"]["AttachmentStatus"];
            /** @description The sniffed type once known. */
            mime?: string | null;
            /**
             * Format: int64
             * @description Stored size after processing.
             */
            bytes?: number | null;
            width?: number | null;
            height?: number | null;
            duration_ms?: number | null;
            /** @description Shown to the uploader when `status` is `rejected`. */
            reject_reason?: string | null;
            /** @description Signed GET URLs. Present only when `status` is `ready`. */
            urls?: components["schemas"]["AttachmentUrls"] | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            ready_at?: string | null;
        };
        /** @enum {string} */
        NotificationKind: "member_joined" | "terms_changed" | "terms_signed" | "pact_scheduled" | "pact_settled" | "proof_submitted" | "proof_edited" | "proof_approved" | "proof_rejected" | "proof_auto_approved" | "proof_overridden" | "rejection_final" | "rest_declared" | "day_missed" | "dispute_opened" | "dispute_upheld" | "dispute_dismissed" | "reminder_cutoff_3h" | "reminder_cutoff_30m" | "review_deadline_soon" | "payout_marked_paid" | "payout_confirmed";
        Notification: {
            /** Format: int64 */
            id: number;
            kind: components["schemas"]["NotificationKind"];
            /** @description Carries `pact_id` and, where relevant, `check_in_id`, so the client can deep-link. */
            payload: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            read_at?: string | null;
            /** Format: date-time */
            created_at: string;
        };
        NotificationPage: {
            items: components["schemas"]["Notification"][];
            next_cursor: string | null;
            unread_count: number;
        };
        MarkReadRequest: {
            ids: number[];
        };
        Health: {
            /** @enum {string} */
            status: "ok";
        };
        Readiness: {
            /** @enum {string} */
            status: "ok" | "degraded";
            checks: {
                /** @enum {string} */
                database: "ok" | "down";
                /** @enum {string} */
                redis: "ok" | "down";
                /** @enum {string} */
                storage: "ok" | "down";
            };
        };
    };
    responses: {
        /** @description An error. Branch on `code`. */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        PactId: string;
        CheckInId: string;
        AttachmentId: string;
        /** @description The one-time invite token from `proposePact`. */
        InviteToken: string;
        /**
         * @description Client-generated unique value (a UUID is fine) for one logical action. A retry with the same
         *     key replays the stored response for 24 hours instead of acting twice.
         */
        IdempotencyKey: string;
        /** @description Opaque value from the previous page's `next_cursor`. */
        Cursor: string;
        Limit: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Account created and signed in. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            "4XX": components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Signed in. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            "4XX": components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Signed out. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            "4XX": components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The current user. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            "4XX": components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    updateMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMeRequest"];
            };
        };
        responses: {
            /** @description The updated user. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            "4XX": components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description Password changed; other sessions ended. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            "4XX": components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    getToday: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The Today aggregate. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Today"];
                };
            };
            "4XX": components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    listPacts: {
        parameters: {
            query?: {
                /** @description Opaque value from the previous page's `next_cursor`. */
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of pacts. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PactPage"];
                };
            };
            "4XX": components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    createPact: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description Client-generated unique value (a UUID is fine) for one logical action. A retry with the same
                 *     key replays the stored response for 24 hours instead of acting twice.
                 */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PactDraft"];
            };
        };
        responses: {
            /** @description The new draft. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pact"];
                };
            };
            "4XX": components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    getPact: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pactId: components["parameters"]["PactId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The pact, its members, the pot balance and the payout once it exists. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pact"];
                };
            };
            "4XX": components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    updatePact: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description Client-generated unique value (a UUID is fine) for one logical action. A retry with the same
                 *     key replays the stored response for 24 hours instead of acting twice.
                 */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path: {
                pactId: components["parameters"]["PactId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PactDraft"];
            };
        };
        responses: {
            /** @description The updated pact. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pact"];
                };
            };
            "4XX": components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    proposePact: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description Client-generated unique value (a UUID is fine) for one logical action. A retry with the same
                 *     key replays the stored response for 24 hours instead of acting twice.
                 */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path: {
                pactId: components["parameters"]["PactId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ProposeRequest"];
            };
        };
        responses: {
            /** @description The invite. The link is `/invite/{invite_token}` on the web app. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Proposal"];
                };
            };
            "4XX": components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    acceptPact: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description Client-generated unique value (a UUID is fine) for one logical action. A retry with the same
                 *     key replays the stored response for 24 hours instead of acting twice.
                 */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path: {
                pactId: components["parameters"]["PactId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AcceptRequest"];
            };
        };
        responses: {
            /** @description The pact after signing. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pact"];
                };
            };
            "4XX": components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    previewInvite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The one-time invite token from `proposePact`. */
                token: components["parameters"]["InviteToken"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The invite preview. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvitePreview"];
                };
            };
            "4XX": components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    joinInvite: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description Client-generated unique value (a UUID is fine) for one logical action. A retry with the same
                 *     key replays the stored response for 24 hours instead of acting twice.
                 */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path: {
                /** @description The one-time invite token from `proposePact`. */
                token: components["parameters"]["InviteToken"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The pact, now with both members. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pact"];
                };
            };
            "4XX": components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    listPactCheckIns: {
        parameters: {
            query?: {
                /** @description First `local_date` to include. Defaults to the pact start. */
                from?: string;
                /** @description Last `local_date` to include. Defaults to the pact end. */
                to?: string;
            };
            header?: never;
            path: {
                pactId: components["parameters"]["PactId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The check-ins in range. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckInList"];
                };
            };
            "4XX": components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    getCheckIn: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                checkInId: components["parameters"]["CheckInId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The check-in with everything around it. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckInDetail"];
                };
            };
            "4XX": components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    submitProof: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description Client-generated unique value (a UUID is fine) for one logical action. A retry with the same
                 *     key replays the stored response for 24 hours instead of acting twice.
                 */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path: {
                checkInId: components["parameters"]["CheckInId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProofRequest"];
            };
        };
        responses: {
            /** @description The check-in after submission. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckInDetail"];
                };
            };
            "4XX": components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    declareRest: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description Client-generated unique value (a UUID is fine) for one logical action. A retry with the same
                 *     key replays the stored response for 24 hours instead of acting twice.
                 */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path: {
                checkInId: components["parameters"]["CheckInId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The check-in, now `rest`. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckInDetail"];
                };
            };
            "4XX": components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    approveCheckIn: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description Client-generated unique value (a UUID is fine) for one logical action. A retry with the same
                 *     key replays the stored response for 24 hours instead of acting twice.
                 */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path: {
                checkInId: components["parameters"]["CheckInId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The check-in, now `approved`. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckInDetail"];
                };
            };
            "4XX": components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    rejectCheckIn: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description Client-generated unique value (a UUID is fine) for one logical action. A retry with the same
                 *     key replays the stored response for 24 hours instead of acting twice.
                 */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path: {
                checkInId: components["parameters"]["CheckInId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReasonRequest"];
            };
        };
        responses: {
            /** @description The check-in, now `rejected`. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckInDetail"];
                };
            };
            "4XX": components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    overrideCheckIn: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description Client-generated unique value (a UUID is fine) for one logical action. A retry with the same
                 *     key replays the stored response for 24 hours instead of acting twice.
                 */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path: {
                checkInId: components["parameters"]["CheckInId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReasonRequest"];
            };
        };
        responses: {
            /** @description The check-in, now final `rejected`. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckInDetail"];
                };
            };
            "4XX": components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    disputeCheckIn: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description Client-generated unique value (a UUID is fine) for one logical action. A retry with the same
                 *     key replays the stored response for 24 hours instead of acting twice.
                 */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path: {
                checkInId: components["parameters"]["CheckInId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReasonRequest"];
            };
        };
        responses: {
            /** @description The check-in, now `disputed`. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckInDetail"];
                };
            };
            "4XX": components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    resolveDispute: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description Client-generated unique value (a UUID is fine) for one logical action. A retry with the same
                 *     key replays the stored response for 24 hours instead of acting twice.
                 */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path: {
                checkInId: components["parameters"]["CheckInId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResolveDisputeRequest"];
            };
        };
        responses: {
            /** @description The check-in, now `approved` or final `rejected`. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckInDetail"];
                };
            };
            "4XX": components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    getReviewQueue: {
        parameters: {
            query?: {
                /** @description Opaque value from the previous page's `next_cursor`. */
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of review items. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewQueuePage"];
                };
            };
            "4XX": components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    listLedger: {
        parameters: {
            query?: {
                /** @description Opaque value from the previous page's `next_cursor`. */
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path: {
                pactId: components["parameters"]["PactId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of passbook lines. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LedgerPage"];
                };
            };
            "4XX": components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    markPayoutPaid: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description Client-generated unique value (a UUID is fine) for one logical action. A retry with the same
                 *     key replays the stored response for 24 hours instead of acting twice.
                 */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path: {
                pactId: components["parameters"]["PactId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["MarkPaidRequest"];
            };
        };
        responses: {
            /** @description The payout. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Payout"];
                };
            };
            "4XX": components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    confirmPayout: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description Client-generated unique value (a UUID is fine) for one logical action. A retry with the same
                 *     key replays the stored response for 24 hours instead of acting twice.
                 */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path: {
                pactId: components["parameters"]["PactId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The payout, now confirmed. The pact is `completed`. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Payout"];
                };
            };
            "4XX": components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    createUpload: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description Client-generated unique value (a UUID is fine) for one logical action. A retry with the same
                 *     key replays the stored response for 24 hours instead of acting twice.
                 */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UploadIntentRequest"];
            };
        };
        responses: {
            /** @description The slot. `headers` must be sent unchanged with the PUT. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadIntent"];
                };
            };
            "4XX": components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    completeUpload: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description Client-generated unique value (a UUID is fine) for one logical action. A retry with the same
                 *     key replays the stored response for 24 hours instead of acting twice.
                 */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path: {
                attachmentId: components["parameters"]["AttachmentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The attachment, now `uploaded` (or already further along on a repeat call). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Attachment"];
                };
            };
            "4XX": components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    getAttachment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attachmentId: components["parameters"]["AttachmentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The attachment. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Attachment"];
                };
            };
            "4XX": components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    listNotifications: {
        parameters: {
            query?: {
                /** @description Opaque value from the previous page's `next_cursor`. */
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
                unread_only?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of notifications. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationPage"];
                };
            };
            "4XX": components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    markNotificationsRead: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description Client-generated unique value (a UUID is fine) for one logical action. A retry with the same
                 *     key replays the stored response for 24 hours instead of acting twice.
                 */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MarkReadRequest"];
            };
        };
        responses: {
            /** @description Marked. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            "4XX": components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Alive. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            "4XX": components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    getReadiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ready. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Readiness"];
                };
            };
            /** @description At least one dependency is down. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Readiness"];
                };
            };
            "4XX": components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
}
