// An env file for a deploy that runs on this machine or on a CI runner: `https://localhost`,
// Mailpit for mail, fresh secrets, and the rate limits raised for a test suite that signs in from
// one IP. Built from the committed staging example, so it can never drift from what `deploy:up`
// expects. Never use it for a real server.
import { setEnvValue, type SecretKind } from "./env.ts";

export function renderLocalStagingEnv(template: string, secret: (kind: SecretKind) => string): string {
  // The template's header tells a person to replace every CHANGE_ME; this file has none to replace.
  const header = "# Generated by `bun run deploy:env-local`. Local and CI only, never for a server.\n";
  let text = template.replace(/^(#[^\n]*\n)+/, header);
  const set = (key: string, value: string) => {
    text = setEnvValue(text, key, value);
  };
  set("APP_BASE_URL", "https://localhost");
  set("DOMAIN", "localhost");
  set("ACME_EMAIL", "");
  set("S3_PUBLIC_ENDPOINT", "https://media.localhost");
  set("MAIL_FROM", '"Tepati Local <no-reply@localhost>"');
  set("GARAGE_CAPACITY", "5G");
  set("SESSION_SECRET", secret("hex32"));
  set("POSTGRES_PASSWORD", secret("hex16"));
  for (const key of ["GARAGE_RPC_SECRET", "GARAGE_ADMIN_TOKEN", "GARAGE_METRICS_TOKEN"]) set(key, secret("hex32"));
  return text.replace(/\n*$/, "\n") + "\n# Local and CI only: the e2e suite signs in far more often than a person does.\nAUTH_RATE_LIMIT_PER_MIN=200\nRATE_LIMIT_PER_MIN=3000\n";
}
